# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("")
        mainWindow.setIconSize(QtCore.QSize(48, 48))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.widgetAppPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.widgetAppPages.setGeometry(QtCore.QRect(0, 90, 800, 510))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetAppPages.setFont(font)
        self.widgetAppPages.setObjectName("widgetAppPages")
        self.widgetPageCustomers = QtWidgets.QWidget()
        self.widgetPageCustomers.setObjectName("widgetPageCustomers")
        self.widgetAppCustomers = QtWidgets.QTreeWidget(self.widgetPageCustomers)
        self.widgetAppCustomers.setGeometry(QtCore.QRect(10, 10, 780, 360))
        self.widgetAppCustomers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetAppCustomers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetAppCustomers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetAppCustomers.setAlternatingRowColors(True)
        self.widgetAppCustomers.setIndentation(20)
        self.widgetAppCustomers.setRootIsDecorated(False)
        self.widgetAppCustomers.setItemsExpandable(False)
        self.widgetAppCustomers.setExpandsOnDoubleClick(False)
        self.widgetAppCustomers.setColumnCount(2)
        self.widgetAppCustomers.setObjectName("widgetAppCustomers")
        self.widgetAppCustomers.header().setDefaultSectionSize(80)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widgetPageCustomers)
        self.layoutWidget_4.setGeometry(QtCore.QRect(220, 380, 271, 86))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.widgetAppCreateCustomer = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.widgetAppCreateCustomer.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCreateCustomer.setObjectName("widgetAppCreateCustomer")
        self.textCustomerName = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerName.setFont(font)
        self.textCustomerName.setObjectName("textCustomerName")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerName, 0, 0, 1, 1)
        self.textCustomerPhone1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerPhone1.setFont(font)
        self.textCustomerPhone1.setObjectName("textCustomerPhone1")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerPhone1, 1, 0, 1, 1)
        self.buttonCreateCustomer = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateCustomer.setFont(font)
        self.buttonCreateCustomer.setObjectName("buttonCreateCustomer")
        self.widgetAppCreateCustomer.addWidget(self.buttonCreateCustomer, 2, 0, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageCustomers)
        self.widgetPageCustomer = QtWidgets.QWidget()
        self.widgetPageCustomer.setObjectName("widgetPageCustomer")
        self.layoutWidget = QtWidgets.QWidget(self.widgetPageCustomer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 360, 190))
        self.layoutWidget.setObjectName("layoutWidget")
        self.widgetAppCustomerBaseData = QtWidgets.QGridLayout(self.layoutWidget)
        self.widgetAppCustomerBaseData.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCustomerBaseData.setObjectName("widgetAppCustomerBaseData")
        self.textFactor = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textFactor.setFont(font)
        self.textFactor.setObjectName("textFactor")
        self.widgetAppCustomerBaseData.addWidget(self.textFactor, 4, 1, 1, 1)
        self.textAddress2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress2.setFont(font)
        self.textAddress2.setObjectName("textAddress2")
        self.widgetAppCustomerBaseData.addWidget(self.textAddress2, 2, 0, 1, 1)
        self.textPhone1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone1.setFont(font)
        self.textPhone1.setObjectName("textPhone1")
        self.widgetAppCustomerBaseData.addWidget(self.textPhone1, 1, 1, 1, 1)
        self.textEmail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEmail.setFont(font)
        self.textEmail.setObjectName("textEmail")
        self.widgetAppCustomerBaseData.addWidget(self.textEmail, 3, 1, 1, 1)
        self.textAddress1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress1.setFont(font)
        self.textAddress1.setObjectName("textAddress1")
        self.widgetAppCustomerBaseData.addWidget(self.textAddress1, 1, 0, 1, 1)
        self.textPhone2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone2.setFont(font)
        self.textPhone2.setObjectName("textPhone2")
        self.widgetAppCustomerBaseData.addWidget(self.textPhone2, 2, 1, 1, 1)
        self.textCompany = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCompany.setFont(font)
        self.textCompany.setObjectName("textCompany")
        self.widgetAppCustomerBaseData.addWidget(self.textCompany, 0, 0, 1, 1)
        self.textAccount = QtWidgets.QLineEdit(self.layoutWidget)
        self.textAccount.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textAccount.setFont(font)
        self.textAccount.setReadOnly(True)
        self.textAccount.setObjectName("textAccount")
        self.widgetAppCustomerBaseData.addWidget(self.textAccount, 0, 1, 1, 1)
        self.textCityName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCityName.setFont(font)
        self.textCityName.setObjectName("textCityName")
        self.widgetAppCustomerBaseData.addWidget(self.textCityName, 4, 0, 1, 1)
        self.textZipCode = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textZipCode.setFont(font)
        self.textZipCode.setObjectName("textZipCode")
        self.widgetAppCustomerBaseData.addWidget(self.textZipCode, 3, 0, 1, 1)
        self.widgetCustomerContacts = QtWidgets.QTreeWidget(self.widgetPageCustomer)
        self.widgetCustomerContacts.setGeometry(QtCore.QRect(10, 320, 530, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCustomerContacts.sizePolicy().hasHeightForWidth())
        self.widgetCustomerContacts.setSizePolicy(sizePolicy)
        self.widgetCustomerContacts.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetCustomerContacts.setIndentation(0)
        self.widgetCustomerContacts.setRootIsDecorated(False)
        self.widgetCustomerContacts.setItemsExpandable(False)
        self.widgetCustomerContacts.setExpandsOnDoubleClick(False)
        self.widgetCustomerContacts.setObjectName("widgetCustomerContacts")
        self.textCustomerNotes = QtWidgets.QTextEdit(self.widgetPageCustomer)
        self.textCustomerNotes.setGeometry(QtCore.QRect(10, 210, 360, 101))
        self.textCustomerNotes.setObjectName("textCustomerNotes")
        self.buttonArchiveContacts = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveContacts.setGeometry(QtCore.QRect(560, 397, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveContacts.setFont(font)
        self.buttonArchiveContacts.setObjectName("buttonArchiveContacts")
        self.buttonCreateContact = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonCreateContact.setGeometry(QtCore.QRect(560, 320, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateContact.setFont(font)
        self.buttonCreateContact.setObjectName("buttonCreateContact")
        self.buttonArchiveCustomer = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveCustomer.setGeometry(QtCore.QRect(560, 210, 220, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveCustomer.setFont(font)
        self.buttonArchiveCustomer.setObjectName("buttonArchiveCustomer")
        self.widgetCustomerProducts = QtWidgets.QTableWidget(self.widgetPageCustomer)
        self.widgetCustomerProducts.setGeometry(QtCore.QRect(380, 10, 410, 192))
        self.widgetCustomerProducts.setObjectName("widgetCustomerProducts")
        self.widgetCustomerProducts.setColumnCount(4)
        self.widgetCustomerProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(3, item)
        self.widgetAppPages.addWidget(self.widgetPageCustomer)
        self.widgetPageCustomerVisits = QtWidgets.QWidget()
        self.widgetPageCustomerVisits.setObjectName("widgetPageCustomerVisits")
        self.widgetCustomerVisits = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetCustomerVisits.setGeometry(QtCore.QRect(10, 10, 640, 170))
        self.widgetCustomerVisits.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetCustomerVisits.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetCustomerVisits.setAlternatingRowColors(True)
        self.widgetCustomerVisits.setIndentation(0)
        self.widgetCustomerVisits.setRootIsDecorated(False)
        self.widgetCustomerVisits.setItemsExpandable(False)
        self.widgetCustomerVisits.setExpandsOnDoubleClick(False)
        self.widgetCustomerVisits.setObjectName("widgetCustomerVisits")
        self.widgetSingleVisitDetails = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetSingleVisitDetails.setGeometry(QtCore.QRect(10, 180, 780, 140))
        self.widgetSingleVisitDetails.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetSingleVisitDetails.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetSingleVisitDetails.setAlternatingRowColors(True)
        self.widgetSingleVisitDetails.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetSingleVisitDetails.setIndentation(0)
        self.widgetSingleVisitDetails.setRootIsDecorated(False)
        self.widgetSingleVisitDetails.setItemsExpandable(False)
        self.widgetSingleVisitDetails.setObjectName("widgetSingleVisitDetails")
        self.layoutWidget1 = QtWidgets.QWidget(self.widgetPageCustomerVisits)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 330, 220, 160))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.widgetSingleOrderInfo = QtWidgets.QGridLayout(self.layoutWidget1)
        self.widgetSingleOrderInfo.setContentsMargins(0, 0, 0, 0)
        self.widgetSingleOrderInfo.setObjectName("widgetSingleOrderInfo")
        self.labelArchiveSend = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchiveSend.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchiveSend.setObjectName("labelArchiveSend")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveSend, 4, 2, 1, 1)
        self.labelArchiveSendText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchiveSendText.sizePolicy().hasHeightForWidth())
        self.labelArchiveSendText.setSizePolicy(sizePolicy)
        self.labelArchiveSendText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchiveSendText.setFont(font)
        self.labelArchiveSendText.setText("")
        self.labelArchiveSendText.setObjectName("labelArchiveSendText")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveSendText, 4, 3, 1, 1)
        self.labelArchiveOrderSale = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchiveOrderSale.setObjectName("labelArchiveOrderSale")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveOrderSale, 1, 2, 1, 1)
        self.textArchiveSale = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchiveSale.sizePolicy().hasHeightForWidth())
        self.textArchiveSale.setSizePolicy(sizePolicy)
        self.textArchiveSale.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchiveSale.setReadOnly(True)
        self.textArchiveSale.setObjectName("textArchiveSale")
        self.widgetSingleOrderInfo.addWidget(self.textArchiveSale, 1, 3, 1, 1)
        self.labelArchiveSasAmount = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchiveSasAmount.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchiveSasAmount.setObjectName("labelArchiveSasAmount")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveSasAmount, 2, 2, 1, 1)
        self.labelArchiveOrderTotal = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchiveOrderTotal.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchiveOrderTotal.setObjectName("labelArchiveOrderTotal")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveOrderTotal, 3, 2, 1, 1)
        self.textArchiveSas = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchiveSas.sizePolicy().hasHeightForWidth())
        self.textArchiveSas.setSizePolicy(sizePolicy)
        self.textArchiveSas.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchiveSas.setReadOnly(True)
        self.textArchiveSas.setObjectName("textArchiveSas")
        self.widgetSingleOrderInfo.addWidget(self.textArchiveSas, 2, 3, 1, 1)
        self.textArchiveTotal = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchiveTotal.sizePolicy().hasHeightForWidth())
        self.textArchiveTotal.setSizePolicy(sizePolicy)
        self.textArchiveTotal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchiveTotal.setReadOnly(True)
        self.textArchiveTotal.setObjectName("textArchiveTotal")
        self.widgetSingleOrderInfo.addWidget(self.textArchiveTotal, 3, 3, 1, 1)
        self.textArchivePoNumber = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivePoNumber.sizePolicy().hasHeightForWidth())
        self.textArchivePoNumber.setSizePolicy(sizePolicy)
        self.textArchivePoNumber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivePoNumber.setReadOnly(True)
        self.textArchivePoNumber.setObjectName("textArchivePoNumber")
        self.widgetSingleOrderInfo.addWidget(self.textArchivePoNumber, 0, 3, 1, 1)
        self.labelArchivePurchaseOrder = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivePurchaseOrder.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivePurchaseOrder.setObjectName("labelArchivePurchaseOrder")
        self.widgetSingleOrderInfo.addWidget(self.labelArchivePurchaseOrder, 0, 2, 1, 1)
        self.labelArchiveApproved = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchiveApproved.setObjectName("labelArchiveApproved")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveApproved, 5, 2, 1, 1)
        self.labelArchiveApprovedText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchiveApprovedText.sizePolicy().hasHeightForWidth())
        self.labelArchiveApprovedText.setSizePolicy(sizePolicy)
        self.labelArchiveApprovedText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchiveApprovedText.setFont(font)
        self.labelArchiveApprovedText.setText("")
        self.labelArchiveApprovedText.setObjectName("labelArchiveApprovedText")
        self.widgetSingleOrderInfo.addWidget(self.labelArchiveApprovedText, 5, 3, 1, 1)
        self.buttonCreateVisit = QtWidgets.QPushButton(self.widgetPageCustomerVisits)
        self.buttonCreateVisit.setGeometry(QtCore.QRect(670, 20, 120, 27))
        self.buttonCreateVisit.setObjectName("buttonCreateVisit")
        self.textSingleVisitNotes = QtWidgets.QTextEdit(self.widgetPageCustomerVisits)
        self.textSingleVisitNotes.setGeometry(QtCore.QRect(10, 330, 550, 160))
        self.textSingleVisitNotes.setReadOnly(True)
        self.textSingleVisitNotes.setObjectName("textSingleVisitNotes")
        self.widgetAppPages.addWidget(self.widgetPageCustomerVisits)
        self.widgetPagePricelist = QtWidgets.QWidget()
        self.widgetPagePricelist.setObjectName("widgetPagePricelist")
        self.widgetPricelist = QtWidgets.QTreeWidget(self.widgetPagePricelist)
        self.widgetPricelist.setGeometry(QtCore.QRect(10, 10, 780, 330))
        self.widgetPricelist.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.widgetPricelist.setObjectName("widgetPricelist")
        self.widgetPricelist.headerItem().setText(0, "Produkt")
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        self.widgetAppPages.addWidget(self.widgetPagePricelist)
        self.widgetPageReport = QtWidgets.QWidget()
        self.widgetPageReport.setObjectName("widgetPageReport")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widgetPageReport)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 30, 127, 56))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.widgetAppWorkdate = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.widgetAppWorkdate.setContentsMargins(0, 0, 0, 0)
        self.widgetAppWorkdate.setObjectName("widgetAppWorkdate")
        self.buttonCreateReport = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateReport.setFont(font)
        self.buttonCreateReport.setObjectName("buttonCreateReport")
        self.widgetAppWorkdate.addWidget(self.buttonCreateReport, 2, 0, 1, 1)
        self.textWorkdate = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.textWorkdate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textWorkdate.setFont(font)
        self.textWorkdate.setAlignment(QtCore.Qt.AlignCenter)
        self.textWorkdate.setReadOnly(False)
        self.textWorkdate.setObjectName("textWorkdate")
        self.widgetAppWorkdate.addWidget(self.textWorkdate, 1, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.widgetPageReport)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 100, 241, 56))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.widgetAppLastUpdate = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.widgetAppLastUpdate.setContentsMargins(0, 0, 0, 0)
        self.widgetAppLastUpdate.setObjectName("widgetAppLastUpdate")
        self.textCustomerServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerServerDate.setFont(font)
        self.textCustomerServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerServerDate.setReadOnly(True)
        self.textCustomerServerDate.setObjectName("textCustomerServerDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerServerDate, 0, 2, 1, 1)
        self.textCustomerLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerLocalDate.setFont(font)
        self.textCustomerLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerLocalDate.setReadOnly(True)
        self.textCustomerLocalDate.setObjectName("textCustomerLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerLocalDate, 0, 1, 1, 1)
        self.textPricelistServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistServerDate.setFont(font)
        self.textPricelistServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistServerDate.setReadOnly(True)
        self.textPricelistServerDate.setObjectName("textPricelistServerDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistServerDate, 1, 2, 1, 1)
        self.textPricelistLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistLocalDate.setFont(font)
        self.textPricelistLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistLocalDate.setReadOnly(True)
        self.textPricelistLocalDate.setObjectName("textPricelistLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistLocalDate, 1, 1, 1, 1)
        self.buttonGetCustomers = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetCustomers.setObjectName("buttonGetCustomers")
        self.widgetAppLastUpdate.addWidget(self.buttonGetCustomers, 0, 0, 1, 1)
        self.buttonGetPricelist = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetPricelist.setObjectName("buttonGetPricelist")
        self.widgetAppLastUpdate.addWidget(self.buttonGetPricelist, 1, 0, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageReport)
        self.widgetPageReports = QtWidgets.QWidget()
        self.widgetPageReports.setObjectName("widgetPageReports")
        self.treeWidget = QtWidgets.QTreeWidget(self.widgetPageReports)
        self.treeWidget.setGeometry(QtCore.QRect(30, 20, 256, 192))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.label = QtWidgets.QLabel(self.widgetPageReports)
        self.label.setGeometry(QtCore.QRect(380, 170, 150, 60))
        self.label.setObjectName("label")
        self.widgetAppPages.addWidget(self.widgetPageReports)
        self.widgetPageSettings = QtWidgets.QWidget()
        self.widgetPageSettings.setObjectName("widgetPageSettings")
        self.groupSalesPerson = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupSalesPerson.setGeometry(QtCore.QRect(10, 100, 320, 150))
        self.groupSalesPerson.setObjectName("groupSalesPerson")
        self.textAppUserCountry = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserCountry.setGeometry(QtCore.QRect(10, 110, 300, 26))
        self.textAppUserCountry.setMaxLength(2)
        self.textAppUserCountry.setObjectName("textAppUserCountry")
        self.textAppUserPass = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserPass.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppUserPass.setInputMask("")
        self.textAppUserPass.setMaxLength(100)
        self.textAppUserPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textAppUserPass.setObjectName("textAppUserPass")
        self.textAppUserMail = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserMail.setGeometry(QtCore.QRect(10, 30, 300, 28))
        self.textAppUserMail.setText("")
        self.textAppUserMail.setMaxLength(100)
        self.textAppUserMail.setFrame(True)
        self.textAppUserMail.setObjectName("textAppUserMail")
        self.groupInternalServers = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupInternalServers.setGeometry(QtCore.QRect(420, 100, 320, 180))
        self.groupInternalServers.setObjectName("groupInternalServers")
        self.checkServerData = QtWidgets.QCheckBox(self.groupInternalServers)
        self.checkServerData.setGeometry(QtCore.QRect(10, 150, 300, 22))
        self.checkServerData.setObjectName("checkServerData")
        self.textAppDataServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppDataServer.setGeometry(QtCore.QRect(10, 110, 299, 28))
        self.textAppDataServer.setMaxLength(100)
        self.textAppDataServer.setObjectName("textAppDataServer")
        self.textAppMailOrderTo = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailOrderTo.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppMailOrderTo.setText("")
        self.textAppMailOrderTo.setMaxLength(100)
        self.textAppMailOrderTo.setObjectName("textAppMailOrderTo")
        self.textAppMailServerPort = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textAppMailServerPort.setMaxLength(3)
        self.textAppMailServerPort.setObjectName("textAppMailServerPort")
        self.textAppMailServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textAppMailServer.setText("")
        self.textAppMailServer.setMaxLength(100)
        self.textAppMailServer.setObjectName("textAppMailServer")
        self.groupExternalServer = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupExternalServer.setGeometry(QtCore.QRect(420, 330, 320, 150))
        self.groupExternalServer.setObjectName("groupExternalServer")
        self.textExtMailServerUser = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerUser.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textExtMailServerUser.setInputMask("")
        self.textExtMailServerUser.setText("")
        self.textExtMailServerUser.setMaxLength(100)
        self.textExtMailServerUser.setObjectName("textExtMailServerUser")
        self.textExtMailServerPort = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textExtMailServerPort.setMaxLength(3)
        self.textExtMailServerPort.setObjectName("textExtMailServerPort")
        self.textExtMailServerPass = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPass.setGeometry(QtCore.QRect(10, 110, 300, 28))
        self.textExtMailServerPass.setText("")
        self.textExtMailServerPass.setMaxLength(100)
        self.textExtMailServerPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textExtMailServerPass.setObjectName("textExtMailServerPass")
        self.textExtMailServer = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textExtMailServer.setMaxLength(100)
        self.textExtMailServer.setObjectName("textExtMailServer")
        self.databar = QtWidgets.QFrame(self.widgetPageSettings)
        self.databar.setGeometry(QtCore.QRect(0, 0, 801, 90))
        self.databar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(172, 172, 172, 228), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.databar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.databar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.databar.setObjectName("databar")
        self.toolButtonDeleteSalesData = QtWidgets.QToolButton(self.databar)
        self.toolButtonDeleteSalesData.setGeometry(QtCore.QRect(720, 10, 70, 70))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonDeleteSalesData.setIcon(icon)
        self.toolButtonDeleteSalesData.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonDeleteSalesData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonDeleteSalesData.setObjectName("toolButtonDeleteSalesData")
        self.toolButtonImportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportDatabase.setGeometry(QtCore.QRect(80, 10, 70, 70))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/download-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportDatabase.setIcon(icon1)
        self.toolButtonImportDatabase.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonImportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportDatabase.setObjectName("toolButtonImportDatabase")
        self.toolButtonExportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonExportDatabase.setGeometry(QtCore.QRect(10, 10, 70, 70))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/system/database-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExportDatabase.setIcon(icon2)
        self.toolButtonExportDatabase.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonExportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonExportDatabase.setObjectName("toolButtonExportDatabase")
        self.toolButtonImportCsvData = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportCsvData.setGeometry(QtCore.QRect(150, 10, 70, 70))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/system/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportCsvData.setIcon(icon3)
        self.toolButtonImportCsvData.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonImportCsvData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportCsvData.setObjectName("toolButtonImportCsvData")
        self.toolButtonArchiveSettings = QtWidgets.QToolButton(self.databar)
        self.toolButtonArchiveSettings.setGeometry(QtCore.QRect(580, 10, 70, 70))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/system/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonArchiveSettings.setIcon(icon4)
        self.toolButtonArchiveSettings.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonArchiveSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonArchiveSettings.setObjectName("toolButtonArchiveSettings")
        self.widgetAppPages.addWidget(self.widgetPageSettings)
        self.widgetPageInfo = QtWidgets.QWidget()
        self.widgetPageInfo.setObjectName("widgetPageInfo")
        self.label_2 = QtWidgets.QLabel(self.widgetPageInfo)
        self.label_2.setGeometry(QtCore.QRect(250, 210, 161, 71))
        self.label_2.setObjectName("label_2")
        self.widgetAppPages.addWidget(self.widgetPageInfo)
        self.widgetPageVisit = QtWidgets.QWidget()
        self.widgetPageVisit.setObjectName("widgetPageVisit")
        self.widgetVisit = QtWidgets.QTableWidget(self.widgetPageVisit)
        self.widgetVisit.setGeometry(QtCore.QRect(10, 320, 780, 180))
        self.widgetVisit.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.widgetVisit.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetVisit.setObjectName("widgetVisit")
        self.widgetVisit.setColumnCount(10)
        self.widgetVisit.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(9, item)
        self.widgetVisit.horizontalHeader().setDefaultSectionSize(70)
        self.widgetVisit.horizontalHeader().setMinimumSectionSize(10)
        self.widgetVisit.verticalHeader().setStretchLastSection(True)
        self.formLayoutWidget = QtWidgets.QWidget(self.widgetPageVisit)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 320, 180))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formVisit = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formVisit.setContentsMargins(0, 0, 0, 0)
        self.formVisit.setObjectName("formVisit")
        self.textVisitDate = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textVisitDate.setEnabled(True)
        self.textVisitDate.setReadOnly(True)
        self.textVisitDate.setObjectName("textVisitDate")
        self.formVisit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textVisitDate)
        self.textOrderBuyer = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textOrderBuyer.setObjectName("textOrderBuyer")
        self.formVisit.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textOrderBuyer)
        self.textOrderPo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textOrderPo.setObjectName("textOrderPo")
        self.formVisit.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textOrderPo)
        self.textVisitProductDemo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textVisitProductDemo.setReadOnly(True)
        self.textVisitProductDemo.setObjectName("textVisitProductDemo")
        self.formVisit.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textVisitProductDemo)
        self.textVisitProductSale = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textVisitProductSale.setReadOnly(True)
        self.textVisitProductSale.setObjectName("textVisitProductSale")
        self.formVisit.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textVisitProductSale)
        self.textOrderNote = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.textOrderNote.setObjectName("textOrderNote")
        self.formVisit.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textOrderNote)
        self.vertialLine = QtWidgets.QFrame(self.widgetPageVisit)
        self.vertialLine.setGeometry(QtCore.QRect(330, 50, 16, 180))
        self.vertialLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertialLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertialLine.setObjectName("vertialLine")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widgetPageVisit)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(339, 50, 291, 181))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.widgetDeliveryAddress = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.widgetDeliveryAddress.setContentsMargins(0, 0, 0, 0)
        self.widgetDeliveryAddress.setObjectName("widgetDeliveryAddress")
        self.textPoCompany = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoCompany.setObjectName("textPoCompany")
        self.widgetDeliveryAddress.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textPoCompany)
        self.textPoAddress1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoAddress1.setObjectName("textPoAddress1")
        self.widgetDeliveryAddress.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textPoAddress1)
        self.textPoAddress2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoAddress2.setObjectName("textPoAddress2")
        self.widgetDeliveryAddress.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textPoAddress2)
        self.textPoZip = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoZip.setObjectName("textPoZip")
        self.widgetDeliveryAddress.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textPoZip)
        self.textPoCity = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoCity.setObjectName("textPoCity")
        self.widgetDeliveryAddress.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textPoCity)
        self.textPoCountry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.textPoCountry.setObjectName("textPoCountry")
        self.widgetDeliveryAddress.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textPoCountry)
        self.gridLayoutWidget = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 150, 151, 86))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.widgetTotals = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.widgetTotals.setContentsMargins(0, 0, 0, 0)
        self.widgetTotals.setObjectName("widgetTotals")
        self.textVisitSas = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSas.setEnabled(True)
        self.textVisitSas.setReadOnly(True)
        self.textVisitSas.setObjectName("textVisitSas")
        self.widgetTotals.addWidget(self.textVisitSas, 2, 1, 1, 1)
        self.labelVisitSale = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelVisitSale.setObjectName("labelVisitSale")
        self.widgetTotals.addWidget(self.labelVisitSale, 1, 0, 1, 1)
        self.textVisitSale = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSale.setEnabled(True)
        self.textVisitSale.setReadOnly(True)
        self.textVisitSale.setObjectName("textVisitSale")
        self.widgetTotals.addWidget(self.textVisitSale, 1, 1, 1, 1)
        self.labelVisitSas = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelVisitSas.setObjectName("labelVisitSas")
        self.widgetTotals.addWidget(self.labelVisitSas, 2, 0, 1, 1)
        self.labelVisitTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelVisitTotal.setObjectName("labelVisitTotal")
        self.widgetTotals.addWidget(self.labelVisitTotal, 3, 0, 1, 1)
        self.textOrderTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textOrderTotal.setEnabled(True)
        self.textOrderTotal.setReadOnly(True)
        self.textOrderTotal.setObjectName("textOrderTotal")
        self.widgetTotals.addWidget(self.textOrderTotal, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 621, 35))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.widgetCustomerVisitDetails = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.widgetCustomerVisitDetails.setContentsMargins(0, 0, 0, 0)
        self.widgetCustomerVisitDetails.setObjectName("widgetCustomerVisitDetails")
        self.labelCompany = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCompany.setFont(font)
        self.labelCompany.setObjectName("labelCompany")
        self.widgetCustomerVisitDetails.addWidget(self.labelCompany, 0, 0, 1, 1)
        self.textVisitCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textVisitCompany.setFont(font)
        self.textVisitCompany.setReadOnly(True)
        self.textVisitCompany.setObjectName("textVisitCompany")
        self.widgetCustomerVisitDetails.addWidget(self.textVisitCompany, 0, 1, 1, 1)
        self.buttonInsertDemo = QtWidgets.QPushButton(self.widgetPageVisit)
        self.buttonInsertDemo.setGeometry(QtCore.QRect(640, 10, 150, 60))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/system/item-configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInsertDemo.setIcon(icon5)
        self.buttonInsertDemo.setIconSize(QtCore.QSize(48, 48))
        self.buttonInsertDemo.setObjectName("buttonInsertDemo")
        self.buttonInsertSale = QtWidgets.QPushButton(self.widgetPageVisit)
        self.buttonInsertSale.setGeometry(QtCore.QRect(640, 80, 150, 60))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/system/product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonInsertSale.setIcon(icon6)
        self.buttonInsertSale.setIconSize(QtCore.QSize(48, 48))
        self.buttonInsertSale.setDefault(True)
        self.buttonInsertSale.setObjectName("buttonInsertSale")
        self.buttonArchiveVisit = QtWidgets.QPushButton(self.widgetPageVisit)
        self.buttonArchiveVisit.setGeometry(QtCore.QRect(640, 250, 150, 60))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/system/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonArchiveVisit.setIcon(icon7)
        self.buttonArchiveVisit.setIconSize(QtCore.QSize(48, 48))
        self.buttonArchiveVisit.setObjectName("buttonArchiveVisit")
        self.textVisitNotes = QtWidgets.QTextEdit(self.widgetPageVisit)
        self.textVisitNotes.setGeometry(QtCore.QRect(10, 230, 620, 80))
        self.textVisitNotes.setObjectName("textVisitNotes")
        self.widgetAppPages.addWidget(self.widgetPageVisit)
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(172, 172, 172, 228), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.toolButtonReport = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReport.setGeometry(QtCore.QRect(290, 10, 70, 70))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/system/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReport.setIcon(icon8)
        self.toolButtonReport.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReport.setCheckable(True)
        self.toolButtonReport.setChecked(True)
        self.toolButtonReport.setAutoExclusive(True)
        self.toolButtonReport.setObjectName("toolButtonReport")
        self.toolButtonCustomers = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomers.setGeometry(QtCore.QRect(10, 10, 70, 70))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/system/companies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomers.setIcon(icon9)
        self.toolButtonCustomers.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomers.setCheckable(True)
        self.toolButtonCustomers.setAutoExclusive(True)
        self.toolButtonCustomers.setObjectName("toolButtonCustomers")
        self.toolButtonCustomer = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomer.setGeometry(QtCore.QRect(80, 10, 70, 70))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/system/company.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomer.setIcon(icon10)
        self.toolButtonCustomer.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomer.setCheckable(True)
        self.toolButtonCustomer.setAutoExclusive(True)
        self.toolButtonCustomer.setObjectName("toolButtonCustomer")
        self.toolButtonCustomerVisits = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomerVisits.setGeometry(QtCore.QRect(150, 10, 70, 70))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/system/car-large.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomerVisits.setIcon(icon11)
        self.toolButtonCustomerVisits.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomerVisits.setCheckable(True)
        self.toolButtonCustomerVisits.setAutoExclusive(True)
        self.toolButtonCustomerVisits.setObjectName("toolButtonCustomerVisits")
        self.toolButtonPricelist = QtWidgets.QToolButton(self.topbar)
        self.toolButtonPricelist.setGeometry(QtCore.QRect(220, 10, 70, 70))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/system/catalog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPricelist.setIcon(icon12)
        self.toolButtonPricelist.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonPricelist.setCheckable(True)
        self.toolButtonPricelist.setAutoExclusive(True)
        self.toolButtonPricelist.setObjectName("toolButtonPricelist")
        self.toolButtonSettings = QtWidgets.QToolButton(self.topbar)
        self.toolButtonSettings.setGeometry(QtCore.QRect(580, 10, 70, 70))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/system/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSettings.setIcon(icon13)
        self.toolButtonSettings.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonSettings.setCheckable(True)
        self.toolButtonSettings.setAutoExclusive(True)
        self.toolButtonSettings.setObjectName("toolButtonSettings")
        self.toolButtonExit = QtWidgets.QToolButton(self.topbar)
        self.toolButtonExit.setGeometry(QtCore.QRect(720, 10, 70, 70))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/system/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExit.setIcon(icon14)
        self.toolButtonExit.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonExit.setCheckable(True)
        self.toolButtonExit.setAutoExclusive(True)
        self.toolButtonExit.setObjectName("toolButtonExit")
        self.toolButtonReports = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReports.setGeometry(QtCore.QRect(360, 10, 70, 70))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/system/reports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReports.setIcon(icon15)
        self.toolButtonReports.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReports.setCheckable(True)
        self.toolButtonReports.setAutoExclusive(True)
        self.toolButtonReports.setObjectName("toolButtonReports")
        self.toolButtonInfo = QtWidgets.QToolButton(self.topbar)
        self.toolButtonInfo.setGeometry(QtCore.QRect(650, 10, 70, 70))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/system/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonInfo.setIcon(icon16)
        self.toolButtonInfo.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonInfo.setCheckable(True)
        self.toolButtonInfo.setAutoExclusive(True)
        self.toolButtonInfo.setObjectName("toolButtonInfo")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.widgetAppPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Eordre"))
        self.widgetAppCustomers.headerItem().setText(0, _translate("mainWindow", "Telefon"))
        self.widgetAppCustomers.headerItem().setText(1, _translate("mainWindow", "Firmanavn"))
        self.textCustomerName.setToolTip(_translate("mainWindow", "navn for ny kunde"))
        self.textCustomerName.setStatusTip(_translate("mainWindow", "Her indsættes firmanavn for kunde der skal oprettes"))
        self.textCustomerName.setPlaceholderText(_translate("mainWindow", "navn"))
        self.textCustomerPhone1.setToolTip(_translate("mainWindow", "telefon for ny kunde"))
        self.textCustomerPhone1.setStatusTip(_translate("mainWindow", "Her indsættes telefon nummer for kunde der skal oprettes\n"
"                                                "))
        self.textCustomerPhone1.setPlaceholderText(_translate("mainWindow", "telefon"))
        self.buttonCreateCustomer.setToolTip(_translate("mainWindow", "Opret ny kunde"))
        self.buttonCreateCustomer.setStatusTip(_translate("mainWindow", "Udfyld felterne og tryk her for at oprette firma"))
        self.buttonCreateCustomer.setText(_translate("mainWindow", "Opret kunde"))
        self.textFactor.setToolTip(_translate("mainWindow", "Faktor"))
        self.textFactor.setStatusTip(_translate("mainWindow", "Ved salg bliver liste priser ganget med\n"
"                                                                        faktor\n"
"                                                                    "))
        self.textFactor.setPlaceholderText(_translate("mainWindow", "faktor"))
        self.textAddress2.setToolTip(_translate("mainWindow", "Udvidet adresse"))
        self.textAddress2.setStatusTip(_translate("mainWindow", "Dette felt er udvidet adresse"))
        self.textAddress2.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone1.setToolTip(_translate("mainWindow", "Primær telefon"))
        self.textPhone1.setStatusTip(_translate("mainWindow", "Dette felt er primær telefon til kunde\n"
"                                                                    "))
        self.textPhone1.setPlaceholderText(_translate("mainWindow", "primær telefon"))
        self.textEmail.setToolTip(_translate("mainWindow", "Epost adresse"))
        self.textEmail.setStatusTip(_translate("mainWindow", "Dette felt er epost adresse for kunde\n"
"                                                                    "))
        self.textEmail.setPlaceholderText(_translate("mainWindow", "epost adresse"))
        self.textAddress1.setToolTip(_translate("mainWindow", "Kundens adresse"))
        self.textAddress1.setStatusTip(_translate("mainWindow", "Dette felt er kunde adresse"))
        self.textAddress1.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone2.setToolTip(_translate("mainWindow", "Anden telefon"))
        self.textPhone2.setStatusTip(_translate("mainWindow", "Dette felt er mobil eller anden telefon til\n"
"                                                                        kunde\n"
"                                                                    "))
        self.textPhone2.setPlaceholderText(_translate("mainWindow", "mobil telefon"))
        self.textCompany.setToolTip(_translate("mainWindow", "Firmanavn"))
        self.textCompany.setStatusTip(_translate("mainWindow", "Dette felt er kunde navn"))
        self.textCompany.setPlaceholderText(_translate("mainWindow", "firma navn"))
        self.textAccount.setToolTip(_translate("mainWindow", "Kundekonto"))
        self.textAccount.setStatusTip(_translate("mainWindow", "Dette felt er konto for kunde"))
        self.textAccount.setPlaceholderText(_translate("mainWindow", "konto"))
        self.textCityName.setToolTip(_translate("mainWindow", "Bynavn"))
        self.textCityName.setStatusTip(_translate("mainWindow", "Dette felt er bynavn for kunde"))
        self.textCityName.setPlaceholderText(_translate("mainWindow", "by navn"))
        self.textZipCode.setToolTip(_translate("mainWindow", "Postnummer"))
        self.textZipCode.setStatusTip(_translate("mainWindow", "Dette felt er postnummer for kunde"))
        self.textZipCode.setPlaceholderText(_translate("mainWindow", "post nummer"))
        self.widgetCustomerContacts.headerItem().setText(0, _translate("mainWindow", "Navn"))
        self.widgetCustomerContacts.headerItem().setText(1, _translate("mainWindow", "Telefon"))
        self.widgetCustomerContacts.headerItem().setText(2, _translate("mainWindow", "Afdeling"))
        self.widgetCustomerContacts.headerItem().setText(3, _translate("mainWindow", "Email"))
        self.widgetCustomerContacts.headerItem().setText(4, _translate("mainWindow", "Info"))
        self.buttonArchiveContacts.setText(_translate("mainWindow", "Arkiver kontakter"))
        self.buttonCreateContact.setText(_translate("mainWindow", "Tilføj kontakt ..."))
        self.buttonArchiveCustomer.setToolTip(_translate("mainWindow", "Arkiver ændringer"))
        self.buttonArchiveCustomer.setStatusTip(_translate("mainWindow", "Tryk her for at gemme rettelser i\n"
"                                                                        databasen\n"
"                                                                    "))
        self.buttonArchiveCustomer.setText(_translate("mainWindow", "Arkiver kunde"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Varenr"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Total"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Bestil"))
        self.widgetCustomerVisits.headerItem().setText(0, _translate("mainWindow", "Id"))
        self.widgetCustomerVisits.headerItem().setText(1, _translate("mainWindow", "Dato"))
        self.widgetCustomerVisits.headerItem().setText(2, _translate("mainWindow", "Navn"))
        self.widgetCustomerVisits.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.widgetCustomerVisits.headerItem().setText(4, _translate("mainWindow", "Salg"))
        self.widgetSingleVisitDetails.headerItem().setText(0, _translate("mainWindow", "*"))
        self.widgetSingleVisitDetails.headerItem().setText(1, _translate("mainWindow", "Ant"))
        self.widgetSingleVisitDetails.headerItem().setText(2, _translate("mainWindow", "SKU"))
        self.widgetSingleVisitDetails.headerItem().setText(3, _translate("mainWindow", "Vare"))
        self.widgetSingleVisitDetails.headerItem().setText(4, _translate("mainWindow", "Pris"))
        self.widgetSingleVisitDetails.headerItem().setText(5, _translate("mainWindow", "%"))
        self.widgetSingleVisitDetails.headerItem().setText(6, _translate("mainWindow", "Ekstra"))
        self.labelArchiveSend.setText(_translate("mainWindow", "Afsl."))
        self.labelArchiveOrderSale.setText(_translate("mainWindow", "Salg"))
        self.labelArchiveSasAmount.setText(_translate("mainWindow", "SAS"))
        self.labelArchiveOrderTotal.setText(_translate("mainWindow", "Total"))
        self.labelArchivePurchaseOrder.setText(_translate("mainWindow", "Rekv."))
        self.labelArchiveApproved.setText(_translate("mainWindow", "Godk."))
        self.buttonCreateVisit.setText(_translate("mainWindow", "Tilføj besøg ..."))
        self.widgetPricelist.headerItem().setText(1, _translate("mainWindow", "Varenr."))
        self.widgetPricelist.headerItem().setText(2, _translate("mainWindow", "Varetekst"))
        self.widgetPricelist.headerItem().setText(3, _translate("mainWindow", "1 stk"))
        self.widgetPricelist.headerItem().setText(4, _translate("mainWindow", "2 stk"))
        self.widgetPricelist.headerItem().setText(5, _translate("mainWindow", "4 stk"))
        self.widgetPricelist.headerItem().setText(6, _translate("mainWindow", "6 stk"))
        self.widgetPricelist.headerItem().setText(7, _translate("mainWindow", "8 stk"))
        self.widgetPricelist.headerItem().setText(8, _translate("mainWindow", "12 stk"))
        self.widgetPricelist.headerItem().setText(9, _translate("mainWindow", "24 stk"))
        self.widgetPricelist.headerItem().setText(10, _translate("mainWindow", "48 stk"))
        self.widgetPricelist.headerItem().setText(11, _translate("mainWindow", "96 stk"))
        self.widgetPricelist.headerItem().setText(12, _translate("mainWindow", "Netto"))
        __sortingEnabled = self.widgetPricelist.isSortingEnabled()
        self.widgetPricelist.setSortingEnabled(False)
        self.widgetPricelist.topLevelItem(0).setText(0, _translate("mainWindow", "sa"))
        self.widgetPricelist.topLevelItem(0).setText(1, _translate("mainWindow", "01,0108"))
        self.widgetPricelist.topLevelItem(0).setText(2, _translate("mainWindow", "Lim-Spray"))
        self.widgetPricelist.topLevelItem(0).setText(3, _translate("mainWindow", "123"))
        self.widgetPricelist.topLevelItem(0).setText(8, _translate("mainWindow", "108"))
        self.widgetPricelist.topLevelItem(0).setText(9, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(0).setText(12, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(1).setText(0, _translate("mainWindow", "qba"))
        self.widgetPricelist.topLevelItem(1).setText(1, _translate("mainWindow", "01,0136"))
        self.widgetPricelist.topLevelItem(1).setText(2, _translate("mainWindow", "Activator Quick Bond"))
        self.widgetPricelist.topLevelItem(1).setText(3, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(6, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(8, _translate("mainWindow", "169"))
        self.widgetPricelist.topLevelItem(1).setText(12, _translate("mainWindow", "161"))
        self.widgetPricelist.setSortingEnabled(__sortingEnabled)
        self.buttonCreateReport.setToolTip(_translate("mainWindow", "Opret dagsrapport"))
        self.buttonCreateReport.setStatusTip(_translate("mainWindow", "Her opretter du en dagsrapport datoen i feltet"))
        self.buttonCreateReport.setText(_translate("mainWindow", "Opret dagsrapport"))
        self.textWorkdate.setToolTip(_translate("mainWindow", "Arbejdsdato"))
        self.textWorkdate.setStatusTip(_translate("mainWindow", "Dette er systemets arbejdsdato"))
        self.textWorkdate.setPlaceholderText(_translate("mainWindow", "arbejdsdato"))
        self.textCustomerServerDate.setToolTip(_translate("mainWindow", "Tilgængelig kundeliste"))
        self.textCustomerServerDate.setStatusTip(_translate("mainWindow", "Dette datoen for serverens kundeliste"))
        self.textCustomerServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.textCustomerLocalDate.setToolTip(_translate("mainWindow", "Kundeliste synkroniseret"))
        self.textCustomerLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af kundeliste"))
        self.textCustomerLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.textPricelistServerDate.setToolTip(_translate("mainWindow", "Tilgængelig prisliste"))
        self.textPricelistServerDate.setStatusTip(_translate("mainWindow", "Dette er datoen for serverens prisliste"))
        self.textPricelistServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.textPricelistLocalDate.setToolTip(_translate("mainWindow", "Prisliste synkroniseret"))
        self.textPricelistLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af prisliste"))
        self.textPricelistLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonGetCustomers.setText(_translate("mainWindow", "Kunder"))
        self.buttonGetPricelist.setText(_translate("mainWindow", "Priser"))
        self.label.setText(_translate("mainWindow", "Rappporter"))
        self.groupSalesPerson.setTitle(_translate("mainWindow", "Sælger"))
        self.textAppUserCountry.setPlaceholderText(_translate("mainWindow", "landkode: dk"))
        self.textAppUserPass.setPlaceholderText(_translate("mainWindow", "din adgangs frase"))
        self.textAppUserMail.setPlaceholderText(_translate("mainWindow", "brugers mail adresse: email@domæne.tld"))
        self.groupInternalServers.setTitle(_translate("mainWindow", "Intern mail og data server"))
        self.checkServerData.setText(_translate("mainWindow", "Ved programstart kontroller server data"))
        self.textAppDataServer.setPlaceholderText(_translate("mainWindow", "webserver: http://localhost:8080"))
        self.textAppMailOrderTo.setPlaceholderText(_translate("mainWindow", "modtager email: email@domain.tld"))
        self.textAppMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textAppMailServer.setPlaceholderText(_translate("mainWindow", "post server: mail.domain.tld"))
        self.groupExternalServer.setTitle(_translate("mainWindow", "Ekstern mailserver"))
        self.textExtMailServerUser.setPlaceholderText(_translate("mainWindow", "post server: brugernavn"))
        self.textExtMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textExtMailServerPass.setPlaceholderText(_translate("mainWindow", "post server: adgangskode"))
        self.textExtMailServer.setPlaceholderText(_translate("mainWindow", "post server: server.domain.tld"))
        self.toolButtonDeleteSalesData.setText(_translate("mainWindow", "SLET"))
        self.toolButtonImportDatabase.setText(_translate("mainWindow", "Import"))
        self.toolButtonExportDatabase.setText(_translate("mainWindow", "Eksport"))
        self.toolButtonImportCsvData.setText(_translate("mainWindow", "CSV data"))
        self.toolButtonArchiveSettings.setText(_translate("mainWindow", "Gem"))
        self.label_2.setText(_translate("mainWindow", "about page"))
        item = self.widgetVisit.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "*"))
        item = self.widgetVisit.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Antal"))
        item = self.widgetVisit.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Produkt"))
        item = self.widgetVisit.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Varenr"))
        item = self.widgetVisit.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Tekst"))
        item = self.widgetVisit.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Pris"))
        item = self.widgetVisit.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "%"))
        item = self.widgetVisit.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Beløb"))
        item = self.widgetVisit.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "SAS"))
        item = self.widgetVisit.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "Note"))
        self.textVisitDate.setPlaceholderText(_translate("mainWindow", "Ordre dato"))
        self.textOrderBuyer.setPlaceholderText(_translate("mainWindow", "Indkøber"))
        self.textOrderPo.setPlaceholderText(_translate("mainWindow", "Rekvisition"))
        self.textVisitProductDemo.setPlaceholderText(_translate("mainWindow", "Produkt demo"))
        self.textVisitProductSale.setPlaceholderText(_translate("mainWindow", "Produkt salg"))
        self.textOrderNote.setPlaceholderText(_translate("mainWindow", "Ordre notat"))
        self.textPoCompany.setPlaceholderText(_translate("mainWindow", "Leveres til"))
        self.textPoAddress1.setPlaceholderText(_translate("mainWindow", "Leverings adresse 1"))
        self.textPoAddress2.setPlaceholderText(_translate("mainWindow", "Leverings adresse 2"))
        self.textPoZip.setPlaceholderText(_translate("mainWindow", "Leverings adresse postnummer"))
        self.textPoCity.setPlaceholderText(_translate("mainWindow", "Leverings adresse bynavn"))
        self.textPoCountry.setPlaceholderText(_translate("mainWindow", "Leverings adresse land"))
        self.labelVisitSale.setText(_translate("mainWindow", "Salg"))
        self.labelVisitSas.setText(_translate("mainWindow", "SAS"))
        self.labelVisitTotal.setText(_translate("mainWindow", "Total"))
        self.labelCompany.setText(_translate("mainWindow", "Kunde"))
        self.buttonInsertDemo.setText(_translate("mainWindow", "Indsæt demo"))
        self.buttonInsertSale.setText(_translate("mainWindow", "Indsæt salg"))
        self.buttonArchiveVisit.setText(_translate("mainWindow", "Arkiver"))
        self.textVisitNotes.setPlaceholderText(_translate("mainWindow", "Besøgs notat"))
        self.toolButtonReport.setToolTip(_translate("mainWindow", "Dagens rapport"))
        self.toolButtonReport.setText(_translate("mainWindow", "..."))
        self.toolButtonCustomers.setToolTip(_translate("mainWindow", "Kunder"))
        self.toolButtonCustomers.setText(_translate("mainWindow", "..."))
        self.toolButtonCustomer.setToolTip(_translate("mainWindow", "Kunde"))
        self.toolButtonCustomer.setText(_translate("mainWindow", "..."))
        self.toolButtonCustomerVisits.setToolTip(_translate("mainWindow", "Kundebesøg"))
        self.toolButtonCustomerVisits.setText(_translate("mainWindow", "..."))
        self.toolButtonPricelist.setToolTip(_translate("mainWindow", "Prisliste"))
        self.toolButtonPricelist.setText(_translate("mainWindow", "..."))
        self.toolButtonSettings.setToolTip(_translate("mainWindow", "Indstillinger"))
        self.toolButtonSettings.setText(_translate("mainWindow", "..."))
        self.toolButtonExit.setToolTip(_translate("mainWindow", "Afslut"))
        self.toolButtonExit.setText(_translate("mainWindow", "..."))
        self.toolButtonReports.setToolTip(_translate("mainWindow", "Rapporter"))
        self.toolButtonReports.setText(_translate("mainWindow", "..."))
        self.toolButtonInfo.setToolTip(_translate("mainWindow", "Info"))
        self.toolButtonInfo.setText(_translate("mainWindow", "..."))

from . import system_rc
