# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/paper-pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")
        mainWindow.setIconSize(QtCore.QSize(48, 48))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.widgetAppPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.widgetAppPages.setGeometry(QtCore.QRect(0, 90, 800, 510))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetAppPages.setFont(font)
        self.widgetAppPages.setObjectName("widgetAppPages")
        self.widgetPageCustomers = QtWidgets.QWidget()
        self.widgetPageCustomers.setObjectName("widgetPageCustomers")
        self.widgetCustomers = QtWidgets.QTreeWidget(self.widgetPageCustomers)
        self.widgetCustomers.setGeometry(QtCore.QRect(0, 30, 800, 480))
        self.widgetCustomers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetCustomers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.widgetCustomers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetCustomers.setAlternatingRowColors(True)
        self.widgetCustomers.setIndentation(0)
        self.widgetCustomers.setRootIsDecorated(False)
        self.widgetCustomers.setItemsExpandable(False)
        self.widgetCustomers.setExpandsOnDoubleClick(False)
        self.widgetCustomers.setColumnCount(7)
        self.widgetCustomers.setObjectName("widgetCustomers")
        self.widgetCustomers.header().setDefaultSectionSize(80)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widgetPageCustomers)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.widgetAppCreateCustomer = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.widgetAppCreateCustomer.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCreateCustomer.setObjectName("widgetAppCreateCustomer")
        self.textCustomerName = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerName.setFont(font)
        self.textCustomerName.setObjectName("textCustomerName")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerName, 0, 0, 1, 1)
        self.textCustomerPhone1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerPhone1.setFont(font)
        self.textCustomerPhone1.setObjectName("textCustomerPhone1")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerPhone1, 0, 1, 1, 1)
        self.buttonCreateCustomer = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateCustomer.setFont(font)
        self.buttonCreateCustomer.setObjectName("buttonCreateCustomer")
        self.widgetAppCreateCustomer.addWidget(self.buttonCreateCustomer, 0, 2, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageCustomers)
        self.widgetPageCustomer = QtWidgets.QWidget()
        self.widgetPageCustomer.setObjectName("widgetPageCustomer")
        self.layoutWidget = QtWidgets.QWidget(self.widgetPageCustomer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 530, 190))
        self.layoutWidget.setObjectName("layoutWidget")
        self.widgetAppCustomer = QtWidgets.QGridLayout(self.layoutWidget)
        self.widgetAppCustomer.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCustomer.setObjectName("widgetAppCustomer")
        self.textFactor = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textFactor.setFont(font)
        self.textFactor.setObjectName("textFactor")
        self.widgetAppCustomer.addWidget(self.textFactor, 4, 1, 1, 1)
        self.textAddress2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress2.setFont(font)
        self.textAddress2.setObjectName("textAddress2")
        self.widgetAppCustomer.addWidget(self.textAddress2, 2, 0, 1, 1)
        self.textPhone1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone1.setFont(font)
        self.textPhone1.setObjectName("textPhone1")
        self.widgetAppCustomer.addWidget(self.textPhone1, 1, 1, 1, 1)
        self.textEmail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEmail.setFont(font)
        self.textEmail.setObjectName("textEmail")
        self.widgetAppCustomer.addWidget(self.textEmail, 3, 1, 1, 1)
        self.textAddress1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress1.setFont(font)
        self.textAddress1.setObjectName("textAddress1")
        self.widgetAppCustomer.addWidget(self.textAddress1, 1, 0, 1, 1)
        self.textPhone2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone2.setFont(font)
        self.textPhone2.setObjectName("textPhone2")
        self.widgetAppCustomer.addWidget(self.textPhone2, 2, 1, 1, 1)
        self.textCompany = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCompany.setFont(font)
        self.textCompany.setObjectName("textCompany")
        self.widgetAppCustomer.addWidget(self.textCompany, 0, 0, 1, 1)
        self.textAccount = QtWidgets.QLineEdit(self.layoutWidget)
        self.textAccount.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textAccount.setFont(font)
        self.textAccount.setReadOnly(True)
        self.textAccount.setObjectName("textAccount")
        self.widgetAppCustomer.addWidget(self.textAccount, 0, 1, 1, 1)
        self.textCityName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCityName.setFont(font)
        self.textCityName.setObjectName("textCityName")
        self.widgetAppCustomer.addWidget(self.textCityName, 4, 0, 1, 1)
        self.textZipCode = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textZipCode.setFont(font)
        self.textZipCode.setObjectName("textZipCode")
        self.widgetAppCustomer.addWidget(self.textZipCode, 3, 0, 1, 1)
        self.widgetCustomerContacts = QtWidgets.QTreeWidget(self.widgetPageCustomer)
        self.widgetCustomerContacts.setGeometry(QtCore.QRect(10, 390, 530, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCustomerContacts.sizePolicy().hasHeightForWidth())
        self.widgetCustomerContacts.setSizePolicy(sizePolicy)
        self.widgetCustomerContacts.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetCustomerContacts.setAlternatingRowColors(True)
        self.widgetCustomerContacts.setIndentation(0)
        self.widgetCustomerContacts.setRootIsDecorated(False)
        self.widgetCustomerContacts.setItemsExpandable(False)
        self.widgetCustomerContacts.setExpandsOnDoubleClick(False)
        self.widgetCustomerContacts.setObjectName("widgetCustomerContacts")
        self.textCustomerNotes = QtWidgets.QTextEdit(self.widgetPageCustomer)
        self.textCustomerNotes.setGeometry(QtCore.QRect(550, 10, 240, 101))
        self.textCustomerNotes.setObjectName("textCustomerNotes")
        self.buttonArchiveContacts = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveContacts.setGeometry(QtCore.QRect(560, 470, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveContacts.setFont(font)
        self.buttonArchiveContacts.setObjectName("buttonArchiveContacts")
        self.buttonCreateContact = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonCreateContact.setGeometry(QtCore.QRect(560, 393, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateContact.setFont(font)
        self.buttonCreateContact.setObjectName("buttonCreateContact")
        self.buttonArchiveCustomer = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveCustomer.setGeometry(QtCore.QRect(560, 170, 220, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveCustomer.setFont(font)
        self.buttonArchiveCustomer.setObjectName("buttonArchiveCustomer")
        self.widgetCustomerProducts = QtWidgets.QTableWidget(self.widgetPageCustomer)
        self.widgetCustomerProducts.setGeometry(QtCore.QRect(10, 210, 530, 170))
        self.widgetCustomerProducts.setAlternatingRowColors(True)
        self.widgetCustomerProducts.setObjectName("widgetCustomerProducts")
        self.widgetCustomerProducts.setColumnCount(4)
        self.widgetCustomerProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(3, item)
        self.widgetAppPages.addWidget(self.widgetPageCustomer)
        self.widgetPageCustomerVisits = QtWidgets.QWidget()
        self.widgetPageCustomerVisits.setObjectName("widgetPageCustomerVisits")
        self.widgetArchivedVisits = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetArchivedVisits.setGeometry(QtCore.QRect(10, 40, 780, 150))
        self.widgetArchivedVisits.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetArchivedVisits.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetArchivedVisits.setAlternatingRowColors(True)
        self.widgetArchivedVisits.setIndentation(0)
        self.widgetArchivedVisits.setRootIsDecorated(False)
        self.widgetArchivedVisits.setItemsExpandable(False)
        self.widgetArchivedVisits.setExpandsOnDoubleClick(False)
        self.widgetArchivedVisits.setObjectName("widgetArchivedVisits")
        self.widgetArchivedOrderLines = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetArchivedOrderLines.setGeometry(QtCore.QRect(10, 200, 780, 130))
        self.widgetArchivedOrderLines.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetArchivedOrderLines.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetArchivedOrderLines.setAlternatingRowColors(True)
        self.widgetArchivedOrderLines.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetArchivedOrderLines.setIndentation(0)
        self.widgetArchivedOrderLines.setRootIsDecorated(False)
        self.widgetArchivedOrderLines.setItemsExpandable(False)
        self.widgetArchivedOrderLines.setObjectName("widgetArchivedOrderLines")
        self.layoutWidget1 = QtWidgets.QWidget(self.widgetPageCustomerVisits)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 340, 220, 160))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.widgetArchivedOrder = QtWidgets.QGridLayout(self.layoutWidget1)
        self.widgetArchivedOrder.setContentsMargins(0, 0, 0, 0)
        self.widgetArchivedOrder.setObjectName("widgetArchivedOrder")
        self.labelArchivedSend = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedSend.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedSend.setObjectName("labelArchivedSend")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSend, 4, 2, 1, 1)
        self.labelArchivedSendText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchivedSendText.sizePolicy().hasHeightForWidth())
        self.labelArchivedSendText.setSizePolicy(sizePolicy)
        self.labelArchivedSendText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchivedSendText.setFont(font)
        self.labelArchivedSendText.setText("")
        self.labelArchivedSendText.setObjectName("labelArchivedSendText")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSendText, 4, 3, 1, 1)
        self.labelArchivedOrderSale = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedOrderSale.setObjectName("labelArchivedOrderSale")
        self.widgetArchivedOrder.addWidget(self.labelArchivedOrderSale, 1, 2, 1, 1)
        self.textArchivedOrderSale = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderSale.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderSale.setSizePolicy(sizePolicy)
        self.textArchivedOrderSale.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderSale.setReadOnly(True)
        self.textArchivedOrderSale.setObjectName("textArchivedOrderSale")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderSale, 1, 3, 1, 1)
        self.labelArchivedSasAmount = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedSasAmount.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedSasAmount.setObjectName("labelArchivedSasAmount")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSasAmount, 2, 2, 1, 1)
        self.labelArchivedOrderTotal = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedOrderTotal.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedOrderTotal.setObjectName("labelArchivedOrderTotal")
        self.widgetArchivedOrder.addWidget(self.labelArchivedOrderTotal, 3, 2, 1, 1)
        self.textArchivedOrderSas = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderSas.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderSas.setSizePolicy(sizePolicy)
        self.textArchivedOrderSas.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderSas.setReadOnly(True)
        self.textArchivedOrderSas.setObjectName("textArchivedOrderSas")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderSas, 2, 3, 1, 1)
        self.textArchivedOrderTotal = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderTotal.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderTotal.setSizePolicy(sizePolicy)
        self.textArchivedOrderTotal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderTotal.setReadOnly(True)
        self.textArchivedOrderTotal.setObjectName("textArchivedOrderTotal")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderTotal, 3, 3, 1, 1)
        self.textArchivedOrderPoNumber = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderPoNumber.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderPoNumber.setSizePolicy(sizePolicy)
        self.textArchivedOrderPoNumber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderPoNumber.setReadOnly(True)
        self.textArchivedOrderPoNumber.setObjectName("textArchivedOrderPoNumber")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderPoNumber, 0, 3, 1, 1)
        self.labelArchivedPurchaseOrder = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedPurchaseOrder.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedPurchaseOrder.setObjectName("labelArchivedPurchaseOrder")
        self.widgetArchivedOrder.addWidget(self.labelArchivedPurchaseOrder, 0, 2, 1, 1)
        self.labelArchivedApproved = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedApproved.setObjectName("labelArchivedApproved")
        self.widgetArchivedOrder.addWidget(self.labelArchivedApproved, 5, 2, 1, 1)
        self.labelArchivedApprovedText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchivedApprovedText.sizePolicy().hasHeightForWidth())
        self.labelArchivedApprovedText.setSizePolicy(sizePolicy)
        self.labelArchivedApprovedText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchivedApprovedText.setFont(font)
        self.labelArchivedApprovedText.setText("")
        self.labelArchivedApprovedText.setObjectName("labelArchivedApprovedText")
        self.widgetArchivedOrder.addWidget(self.labelArchivedApprovedText, 5, 3, 1, 1)
        self.textArchivedVisitNote = QtWidgets.QTextEdit(self.widgetPageCustomerVisits)
        self.textArchivedVisitNote.setGeometry(QtCore.QRect(10, 340, 550, 160))
        self.textArchivedVisitNote.setReadOnly(True)
        self.textArchivedVisitNote.setObjectName("textArchivedVisitNote")
        self.layoutWidget_5 = QtWidgets.QWidget(self.widgetPageCustomerVisits)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 0, 780, 30))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.widgetAppCreateVisit = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.widgetAppCreateVisit.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCreateVisit.setObjectName("widgetAppCreateVisit")
        self.textCustomerNameCreateVisit = QtWidgets.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerNameCreateVisit.setFont(font)
        self.textCustomerNameCreateVisit.setObjectName("textCustomerNameCreateVisit")
        self.widgetAppCreateVisit.addWidget(self.textCustomerNameCreateVisit, 0, 0, 1, 1)
        self.buttonCreateVisit = QtWidgets.QPushButton(self.layoutWidget_5)
        self.buttonCreateVisit.setObjectName("buttonCreateVisit")
        self.widgetAppCreateVisit.addWidget(self.buttonCreateVisit, 0, 1, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageCustomerVisits)
        self.widgetPagePricelist = QtWidgets.QWidget()
        self.widgetPagePricelist.setObjectName("widgetPagePricelist")
        self.widgetPricelist = QtWidgets.QTreeWidget(self.widgetPagePricelist)
        self.widgetPricelist.setGeometry(QtCore.QRect(0, 0, 800, 510))
        self.widgetPricelist.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.widgetPricelist.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.widgetPricelist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetPricelist.setAlternatingRowColors(True)
        self.widgetPricelist.setTextElideMode(QtCore.Qt.ElideNone)
        self.widgetPricelist.setIndentation(0)
        self.widgetPricelist.setUniformRowHeights(True)
        self.widgetPricelist.setItemsExpandable(False)
        self.widgetPricelist.setExpandsOnDoubleClick(False)
        self.widgetPricelist.setObjectName("widgetPricelist")
        self.widgetPricelist.headerItem().setText(0, "Produkt")
        self.widgetPricelist.headerItem().setTextAlignment(3, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(4, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(5, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(6, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(7, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(8, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(9, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(10, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(11, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.widgetPricelist.headerItem().setTextAlignment(12, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        self.widgetAppPages.addWidget(self.widgetPagePricelist)
        self.widgetPageReport = QtWidgets.QWidget()
        self.widgetPageReport.setObjectName("widgetPageReport")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widgetPageReport)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 800, 140))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.widgetAppLastUpdate = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.widgetAppLastUpdate.setContentsMargins(0, 0, 0, 0)
        self.widgetAppLastUpdate.setObjectName("widgetAppLastUpdate")
        self.textPricelistLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistLocalDate.setFont(font)
        self.textPricelistLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistLocalDate.setReadOnly(True)
        self.textPricelistLocalDate.setObjectName("textPricelistLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistLocalDate, 3, 2, 1, 1)
        self.buttonGetPricelist = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetPricelist.setObjectName("buttonGetPricelist")
        self.widgetAppLastUpdate.addWidget(self.buttonGetPricelist, 1, 2, 1, 1)
        self.textPricelistServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistServerDate.setFont(font)
        self.textPricelistServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistServerDate.setReadOnly(True)
        self.textPricelistServerDate.setObjectName("textPricelistServerDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistServerDate, 5, 2, 1, 1)
        self.buttonGetCustomers = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetCustomers.setObjectName("buttonGetCustomers")
        self.widgetAppLastUpdate.addWidget(self.buttonGetCustomers, 1, 3, 1, 1)
        self.textCustomerLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerLocalDate.setFont(font)
        self.textCustomerLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerLocalDate.setReadOnly(True)
        self.textCustomerLocalDate.setObjectName("textCustomerLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerLocalDate, 3, 3, 1, 1)
        self.textCustomerServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerServerDate.setFont(font)
        self.textCustomerServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerServerDate.setReadOnly(True)
        self.textCustomerServerDate.setObjectName("textCustomerServerDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerServerDate, 5, 3, 1, 1)
        self.buttonCreateReport = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateReport.setFont(font)
        self.buttonCreateReport.setObjectName("buttonCreateReport")
        self.widgetAppLastUpdate.addWidget(self.buttonCreateReport, 1, 4, 1, 1)
        self.textWorkdate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textWorkdate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textWorkdate.setFont(font)
        self.textWorkdate.setAlignment(QtCore.Qt.AlignCenter)
        self.textWorkdate.setReadOnly(True)
        self.textWorkdate.setObjectName("textWorkdate")
        self.widgetAppLastUpdate.addWidget(self.textWorkdate, 3, 4, 1, 1)
        self.labelLastUpdated = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelLastUpdated.setObjectName("labelLastUpdated")
        self.widgetAppLastUpdate.addWidget(self.labelLastUpdated, 2, 2, 1, 1)
        self.labelAvailable = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelAvailable.setObjectName("labelAvailable")
        self.widgetAppLastUpdate.addWidget(self.labelAvailable, 4, 2, 1, 1)
        self.widgetReportVisits = QtWidgets.QTreeWidget(self.widgetPageReport)
        self.widgetReportVisits.setGeometry(QtCore.QRect(20, 150, 750, 340))
        self.widgetReportVisits.setAlternatingRowColors(True)
        self.widgetReportVisits.setObjectName("widgetReportVisits")
        self.widgetAppPages.addWidget(self.widgetPageReport)
        self.widgetPageReports = QtWidgets.QWidget()
        self.widgetPageReports.setObjectName("widgetPageReports")
        self.widgetReports = QtWidgets.QTreeWidget(self.widgetPageReports)
        self.widgetReports.setGeometry(QtCore.QRect(0, 0, 800, 510))
        self.widgetReports.setAlternatingRowColors(True)
        self.widgetReports.setIndentation(0)
        self.widgetReports.setObjectName("widgetReports")
        self.widgetReports.headerItem().setText(1, "Dato")
        self.widgetAppPages.addWidget(self.widgetPageReports)
        self.widgetPageSettings = QtWidgets.QWidget()
        self.widgetPageSettings.setObjectName("widgetPageSettings")
        self.groupSalesPerson = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupSalesPerson.setGeometry(QtCore.QRect(10, 100, 320, 150))
        self.groupSalesPerson.setObjectName("groupSalesPerson")
        self.textAppUserCountry = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserCountry.setGeometry(QtCore.QRect(10, 110, 300, 26))
        self.textAppUserCountry.setMaxLength(2)
        self.textAppUserCountry.setObjectName("textAppUserCountry")
        self.textAppUserPass = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserPass.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppUserPass.setInputMask("")
        self.textAppUserPass.setMaxLength(100)
        self.textAppUserPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textAppUserPass.setObjectName("textAppUserPass")
        self.textAppUserMail = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserMail.setGeometry(QtCore.QRect(10, 30, 300, 28))
        self.textAppUserMail.setText("")
        self.textAppUserMail.setMaxLength(100)
        self.textAppUserMail.setFrame(True)
        self.textAppUserMail.setObjectName("textAppUserMail")
        self.groupInternalServers = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupInternalServers.setGeometry(QtCore.QRect(420, 100, 320, 180))
        self.groupInternalServers.setObjectName("groupInternalServers")
        self.checkServerData = QtWidgets.QCheckBox(self.groupInternalServers)
        self.checkServerData.setGeometry(QtCore.QRect(10, 150, 300, 22))
        self.checkServerData.setObjectName("checkServerData")
        self.textAppDataServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppDataServer.setGeometry(QtCore.QRect(10, 110, 299, 28))
        self.textAppDataServer.setMaxLength(100)
        self.textAppDataServer.setObjectName("textAppDataServer")
        self.textAppMailOrderTo = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailOrderTo.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppMailOrderTo.setText("")
        self.textAppMailOrderTo.setMaxLength(100)
        self.textAppMailOrderTo.setObjectName("textAppMailOrderTo")
        self.textAppMailServerPort = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textAppMailServerPort.setMaxLength(3)
        self.textAppMailServerPort.setObjectName("textAppMailServerPort")
        self.textAppMailServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textAppMailServer.setText("")
        self.textAppMailServer.setMaxLength(100)
        self.textAppMailServer.setObjectName("textAppMailServer")
        self.groupExternalServer = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupExternalServer.setGeometry(QtCore.QRect(420, 330, 320, 150))
        self.groupExternalServer.setObjectName("groupExternalServer")
        self.textExtMailServerUser = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerUser.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textExtMailServerUser.setInputMask("")
        self.textExtMailServerUser.setText("")
        self.textExtMailServerUser.setMaxLength(100)
        self.textExtMailServerUser.setObjectName("textExtMailServerUser")
        self.textExtMailServerPort = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textExtMailServerPort.setMaxLength(3)
        self.textExtMailServerPort.setObjectName("textExtMailServerPort")
        self.textExtMailServerPass = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPass.setGeometry(QtCore.QRect(10, 110, 300, 28))
        self.textExtMailServerPass.setText("")
        self.textExtMailServerPass.setMaxLength(100)
        self.textExtMailServerPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textExtMailServerPass.setObjectName("textExtMailServerPass")
        self.textExtMailServer = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textExtMailServer.setMaxLength(100)
        self.textExtMailServer.setObjectName("textExtMailServer")
        self.databar = QtWidgets.QFrame(self.widgetPageSettings)
        self.databar.setGeometry(QtCore.QRect(0, 0, 801, 68))
        self.databar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(172, 172, 172, 228), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.databar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.databar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.databar.setObjectName("databar")
        self.toolButtonDeleteSalesData = QtWidgets.QToolButton(self.databar)
        self.toolButtonDeleteSalesData.setGeometry(QtCore.QRect(290, 10, 50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/remove-from-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonDeleteSalesData.setIcon(icon1)
        self.toolButtonDeleteSalesData.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonDeleteSalesData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonDeleteSalesData.setObjectName("toolButtonDeleteSalesData")
        self.toolButtonImportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportDatabase.setGeometry(QtCore.QRect(70, 10, 50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/system/download-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportDatabase.setIcon(icon2)
        self.toolButtonImportDatabase.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonImportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportDatabase.setObjectName("toolButtonImportDatabase")
        self.toolButtonExportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonExportDatabase.setGeometry(QtCore.QRect(10, 10, 50, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/system/database-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExportDatabase.setIcon(icon3)
        self.toolButtonExportDatabase.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonExportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonExportDatabase.setObjectName("toolButtonExportDatabase")
        self.toolButtonImportCsvData = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportCsvData.setGeometry(QtCore.QRect(230, 10, 50, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/system/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportCsvData.setIcon(icon4)
        self.toolButtonImportCsvData.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonImportCsvData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportCsvData.setObjectName("toolButtonImportCsvData")
        self.toolButtonArchiveSettings = QtWidgets.QToolButton(self.databar)
        self.toolButtonArchiveSettings.setGeometry(QtCore.QRect(740, 10, 50, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/system/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonArchiveSettings.setIcon(icon5)
        self.toolButtonArchiveSettings.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonArchiveSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonArchiveSettings.setObjectName("toolButtonArchiveSettings")
        self.widgetAppPages.addWidget(self.widgetPageSettings)
        self.widgetPageInfo = QtWidgets.QWidget()
        self.widgetPageInfo.setObjectName("widgetPageInfo")
        self.labelAbout = QtWidgets.QLabel(self.widgetPageInfo)
        self.labelAbout.setGeometry(QtCore.QRect(250, 210, 161, 71))
        self.labelAbout.setObjectName("labelAbout")
        self.widgetAppPages.addWidget(self.widgetPageInfo)
        self.widgetPageVisit = QtWidgets.QWidget()
        self.widgetPageVisit.setObjectName("widgetPageVisit")
        self.groupOrderHead = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupOrderHead.setGeometry(QtCore.QRect(400, 0, 400, 220))
        self.groupOrderHead.setObjectName("groupOrderHead")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupOrderHead)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 380, 160))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.widgetVisitHead = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.widgetVisitHead.setContentsMargins(0, 0, 0, 0)
        self.widgetVisitHead.setObjectName("widgetVisitHead")
        self.textVisitProductDemo = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitProductDemo.setFont(font)
        self.textVisitProductDemo.setReadOnly(True)
        self.textVisitProductDemo.setObjectName("textVisitProductDemo")
        self.widgetVisitHead.addWidget(self.textVisitProductDemo, 3, 0, 1, 1)
        self.textVisitDate = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.textVisitDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDate.setFont(font)
        self.textVisitDate.setReadOnly(True)
        self.textVisitDate.setObjectName("textVisitDate")
        self.widgetVisitHead.addWidget(self.textVisitDate, 0, 0, 1, 1)
        self.textVisitDelAddress2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelAddress2.setFont(font)
        self.textVisitDelAddress2.setObjectName("textVisitDelAddress2")
        self.widgetVisitHead.addWidget(self.textVisitDelAddress2, 2, 1, 1, 1)
        self.textVisitPoNumber = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitPoNumber.setFont(font)
        self.textVisitPoNumber.setObjectName("textVisitPoNumber")
        self.widgetVisitHead.addWidget(self.textVisitPoNumber, 2, 0, 1, 1)
        self.textVisitDelAddress1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelAddress1.setFont(font)
        self.textVisitDelAddress1.setObjectName("textVisitDelAddress1")
        self.widgetVisitHead.addWidget(self.textVisitDelAddress1, 1, 1, 1, 1)
        self.textVisitDelCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelCompany.setFont(font)
        self.textVisitDelCompany.setObjectName("textVisitDelCompany")
        self.widgetVisitHead.addWidget(self.textVisitDelCompany, 0, 1, 1, 1)
        self.textVisitProductSale = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitProductSale.setFont(font)
        self.textVisitProductSale.setReadOnly(True)
        self.textVisitProductSale.setObjectName("textVisitProductSale")
        self.widgetVisitHead.addWidget(self.textVisitProductSale, 4, 0, 1, 1)
        self.textVisitDelCity = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelCity.setFont(font)
        self.textVisitDelCity.setObjectName("textVisitDelCity")
        self.widgetVisitHead.addWidget(self.textVisitDelCity, 4, 1, 1, 1)
        self.textVisitDelZip = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelZip.setFont(font)
        self.textVisitDelZip.setObjectName("textVisitDelZip")
        self.widgetVisitHead.addWidget(self.textVisitDelZip, 3, 1, 1, 1)
        self.textVisitBuyer = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitBuyer.setFont(font)
        self.textVisitBuyer.setObjectName("textVisitBuyer")
        self.widgetVisitHead.addWidget(self.textVisitBuyer, 1, 0, 1, 1)
        self.textVisitOrderNote = QtWidgets.QLineEdit(self.groupOrderHead)
        self.textVisitOrderNote.setGeometry(QtCore.QRect(10, 190, 380, 24))
        self.textVisitOrderNote.setMaxLength(100)
        self.textVisitOrderNote.setObjectName("textVisitOrderNote")
        self.groupVisitHead = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupVisitHead.setGeometry(QtCore.QRect(0, 0, 400, 220))
        self.groupVisitHead.setObjectName("groupVisitHead")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupVisitHead)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 380, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridVisitCustomer = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridVisitCustomer.setContentsMargins(0, 0, 0, 0)
        self.gridVisitCustomer.setObjectName("gridVisitCustomer")
        self.textVisitCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitCompany.setFont(font)
        self.textVisitCompany.setReadOnly(True)
        self.textVisitCompany.setObjectName("textVisitCompany")
        self.gridVisitCustomer.addWidget(self.textVisitCompany, 0, 0, 1, 1)
        self.textVisitNote = QtWidgets.QTextEdit(self.groupVisitHead)
        self.textVisitNote.setGeometry(QtCore.QRect(10, 70, 380, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitNote.setFont(font)
        self.textVisitNote.setObjectName("textVisitNote")
        self.buttonArchiveVisit = QtWidgets.QPushButton(self.groupVisitHead)
        self.buttonArchiveVisit.setEnabled(True)
        self.buttonArchiveVisit.setGeometry(QtCore.QRect(10, 170, 380, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveVisit.setFont(font)
        self.buttonArchiveVisit.setAutoDefault(False)
        self.buttonArchiveVisit.setObjectName("buttonArchiveVisit")
        self.textVisitId = QtWidgets.QLineEdit(self.widgetPageVisit)
        self.textVisitId.setEnabled(True)
        self.textVisitId.setGeometry(QtCore.QRect(820, 110, 50, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textVisitId.sizePolicy().hasHeightForWidth())
        self.textVisitId.setSizePolicy(sizePolicy)
        self.textVisitId.setMinimumSize(QtCore.QSize(50, 0))
        self.textVisitId.setMaximumSize(QtCore.QSize(0, 16777215))
        self.textVisitId.setText("")
        self.textVisitId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitId.setReadOnly(True)
        self.textVisitId.setObjectName("textVisitId")
        self.textCustId = QtWidgets.QLineEdit(self.widgetPageVisit)
        self.textCustId.setGeometry(QtCore.QRect(820, 80, 50, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCustId.sizePolicy().hasHeightForWidth())
        self.textCustId.setSizePolicy(sizePolicy)
        self.textCustId.setMinimumSize(QtCore.QSize(50, 0))
        self.textCustId.setMaximumSize(QtCore.QSize(0, 16777215))
        self.textCustId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textCustId.setObjectName("textCustId")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 230, 380, 32))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridVisitProductChoice = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridVisitProductChoice.setContentsMargins(0, 0, 0, 0)
        self.gridVisitProductChoice.setObjectName("gridVisitProductChoice")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridVisitProductChoice.addWidget(self.label, 0, 0, 1, 1)
        self.comboOrderSku = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboOrderSku.setEnabled(True)
        self.comboOrderSku.setMinimumSize(QtCore.QSize(120, 30))
        self.comboOrderSku.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboOrderSku.setFont(font)
        self.comboOrderSku.setEditable(True)
        self.comboOrderSku.setObjectName("comboOrderSku")
        self.gridVisitProductChoice.addWidget(self.comboOrderSku, 0, 3, 1, 1)
        self.comboOrderItem = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboOrderItem.setEnabled(True)
        self.comboOrderItem.setMinimumSize(QtCore.QSize(80, 30))
        self.comboOrderItem.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboOrderItem.setFont(font)
        self.comboOrderItem.setEditable(True)
        self.comboOrderItem.setObjectName("comboOrderItem")
        self.gridVisitProductChoice.addWidget(self.comboOrderItem, 0, 2, 1, 1)
        self.textVisitPcs = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.textVisitPcs.setEnabled(True)
        self.textVisitPcs.setMinimumSize(QtCore.QSize(0, 30))
        self.textVisitPcs.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitPcs.setFont(font)
        self.textVisitPcs.setMaxLength(4)
        self.textVisitPcs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitPcs.setObjectName("textVisitPcs")
        self.gridVisitProductChoice.addWidget(self.textVisitPcs, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(410, 230, 380, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridVisitOrderTotals = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridVisitOrderTotals.setContentsMargins(0, 0, 0, 0)
        self.gridVisitOrderTotals.setObjectName("gridVisitOrderTotals")
        self.labelTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTotal.setFont(font)
        self.labelTotal.setObjectName("labelTotal")
        self.gridVisitOrderTotals.addWidget(self.labelTotal, 0, 4, 1, 1)
        self.textVisitSas = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSas.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitSas.setFont(font)
        self.textVisitSas.setReadOnly(True)
        self.textVisitSas.setObjectName("textVisitSas")
        self.gridVisitOrderTotals.addWidget(self.textVisitSas, 0, 3, 1, 1)
        self.labelSas = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSas.setFont(font)
        self.labelSas.setObjectName("labelSas")
        self.gridVisitOrderTotals.addWidget(self.labelSas, 0, 2, 1, 1)
        self.textVisitSale = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSale.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitSale.setFont(font)
        self.textVisitSale.setReadOnly(True)
        self.textVisitSale.setObjectName("textVisitSale")
        self.gridVisitOrderTotals.addWidget(self.textVisitSale, 0, 1, 1, 1)
        self.textVisitTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitTotal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitTotal.setFont(font)
        self.textVisitTotal.setReadOnly(True)
        self.textVisitTotal.setObjectName("textVisitTotal")
        self.gridVisitOrderTotals.addWidget(self.textVisitTotal, 0, 5, 1, 1)
        self.labelSale = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSale.setFont(font)
        self.labelSale.setObjectName("labelSale")
        self.gridVisitOrderTotals.addWidget(self.labelSale, 0, 0, 1, 1)
        self.groupBoxDemo = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupBoxDemo.setGeometry(QtCore.QRect(10, 270, 301, 180))
        self.groupBoxDemo.setObjectName("groupBoxDemo")
        self.widgetTableDemo = QtWidgets.QTableWidget(self.groupBoxDemo)
        self.widgetTableDemo.setGeometry(QtCore.QRect(0, 20, 230, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetTableDemo.setFont(font)
        self.widgetTableDemo.setLocale(QtCore.QLocale(QtCore.QLocale.Danish, QtCore.QLocale.Denmark))
        self.widgetTableDemo.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.widgetTableDemo.setAlternatingRowColors(True)
        self.widgetTableDemo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetTableDemo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.widgetTableDemo.setCornerButtonEnabled(False)
        self.widgetTableDemo.setColumnCount(3)
        self.widgetTableDemo.setObjectName("widgetTableDemo")
        self.widgetTableDemo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableDemo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableDemo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableDemo.setHorizontalHeaderItem(2, item)
        self.widgetTableDemo.horizontalHeader().setCascadingSectionResizes(True)
        self.widgetTableDemo.horizontalHeader().setDefaultSectionSize(60)
        self.widgetTableDemo.horizontalHeader().setMinimumSectionSize(10)
        self.widgetTableDemo.horizontalHeader().setStretchLastSection(True)
        self.widgetTableDemo.verticalHeader().setMinimumSectionSize(30)
        self.widgetTableDemo.verticalHeader().setStretchLastSection(False)
        self.toolButtonAddDemo = QtWidgets.QToolButton(self.groupBoxDemo)
        self.toolButtonAddDemo.setGeometry(QtCore.QRect(240, 40, 60, 60))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/system/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddDemo.setIcon(icon6)
        self.toolButtonAddDemo.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonAddDemo.setObjectName("toolButtonAddDemo")
        self.toolButtonRemoveDemo = QtWidgets.QToolButton(self.groupBoxDemo)
        self.toolButtonRemoveDemo.setGeometry(QtCore.QRect(240, 110, 60, 60))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/system/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRemoveDemo.setIcon(icon7)
        self.toolButtonRemoveDemo.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonRemoveDemo.setObjectName("toolButtonRemoveDemo")
        self.groupBoxSale = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupBoxSale.setGeometry(QtCore.QRect(320, 270, 471, 180))
        self.groupBoxSale.setObjectName("groupBoxSale")
        self.widgetTableSale = QtWidgets.QTableWidget(self.groupBoxSale)
        self.widgetTableSale.setGeometry(QtCore.QRect(0, 20, 400, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetTableSale.setFont(font)
        self.widgetTableSale.setLocale(QtCore.QLocale(QtCore.QLocale.Danish, QtCore.QLocale.Denmark))
        self.widgetTableSale.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.widgetTableSale.setAlternatingRowColors(True)
        self.widgetTableSale.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetTableSale.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.widgetTableSale.setCornerButtonEnabled(False)
        self.widgetTableSale.setColumnCount(7)
        self.widgetTableSale.setObjectName("widgetTableSale")
        self.widgetTableSale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetTableSale.setHorizontalHeaderItem(6, item)
        self.widgetTableSale.horizontalHeader().setCascadingSectionResizes(True)
        self.widgetTableSale.horizontalHeader().setDefaultSectionSize(60)
        self.widgetTableSale.horizontalHeader().setMinimumSectionSize(10)
        self.widgetTableSale.horizontalHeader().setStretchLastSection(True)
        self.widgetTableSale.verticalHeader().setMinimumSectionSize(30)
        self.widgetTableSale.verticalHeader().setStretchLastSection(False)
        self.toolButtonRemoveSale = QtWidgets.QToolButton(self.groupBoxSale)
        self.toolButtonRemoveSale.setGeometry(QtCore.QRect(410, 110, 60, 60))
        self.toolButtonRemoveSale.setIcon(icon7)
        self.toolButtonRemoveSale.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonRemoveSale.setObjectName("toolButtonRemoveSale")
        self.toolButtonAddSale = QtWidgets.QToolButton(self.groupBoxSale)
        self.toolButtonAddSale.setGeometry(QtCore.QRect(410, 40, 60, 60))
        self.toolButtonAddSale.setIcon(icon6)
        self.toolButtonAddSale.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonAddSale.setObjectName("toolButtonAddSale")
        self.widgetAppPages.addWidget(self.widgetPageVisit)
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(186, 186, 186, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.toolButtonReport = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReport.setGeometry(QtCore.QRect(80, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonReport.setFont(font)
        self.toolButtonReport.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/system/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReport.setIcon(icon8)
        self.toolButtonReport.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReport.setCheckable(True)
        self.toolButtonReport.setChecked(False)
        self.toolButtonReport.setAutoExclusive(True)
        self.toolButtonReport.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonReport.setObjectName("toolButtonReport")
        self.toolButtonCustomers = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomers.setGeometry(QtCore.QRect(150, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomers.setFont(font)
        self.toolButtonCustomers.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/system/companies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomers.setIcon(icon9)
        self.toolButtonCustomers.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomers.setCheckable(True)
        self.toolButtonCustomers.setAutoExclusive(True)
        self.toolButtonCustomers.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomers.setObjectName("toolButtonCustomers")
        self.toolButtonCustomer = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomer.setGeometry(QtCore.QRect(220, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomer.setFont(font)
        self.toolButtonCustomer.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/system/company.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomer.setIcon(icon10)
        self.toolButtonCustomer.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomer.setCheckable(True)
        self.toolButtonCustomer.setAutoExclusive(True)
        self.toolButtonCustomer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomer.setObjectName("toolButtonCustomer")
        self.toolButtonCustomerVisits = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomerVisits.setGeometry(QtCore.QRect(290, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomerVisits.setFont(font)
        self.toolButtonCustomerVisits.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/system/order-history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomerVisits.setIcon(icon11)
        self.toolButtonCustomerVisits.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomerVisits.setCheckable(True)
        self.toolButtonCustomerVisits.setAutoExclusive(True)
        self.toolButtonCustomerVisits.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomerVisits.setObjectName("toolButtonCustomerVisits")
        self.toolButtonPricelist = QtWidgets.QToolButton(self.topbar)
        self.toolButtonPricelist.setGeometry(QtCore.QRect(430, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonPricelist.setFont(font)
        self.toolButtonPricelist.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/system/catalog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPricelist.setIcon(icon12)
        self.toolButtonPricelist.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonPricelist.setCheckable(True)
        self.toolButtonPricelist.setAutoExclusive(True)
        self.toolButtonPricelist.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonPricelist.setObjectName("toolButtonPricelist")
        self.toolButtonReports = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReports.setGeometry(QtCore.QRect(10, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonReports.setFont(font)
        self.toolButtonReports.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/system/reports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReports.setIcon(icon13)
        self.toolButtonReports.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReports.setCheckable(True)
        self.toolButtonReports.setAutoExclusive(True)
        self.toolButtonReports.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonReports.setObjectName("toolButtonReports")
        self.toolButtonInfo = QtWidgets.QToolButton(self.topbar)
        self.toolButtonInfo.setGeometry(QtCore.QRect(650, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonInfo.setFont(font)
        self.toolButtonInfo.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/system/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonInfo.setIcon(icon14)
        self.toolButtonInfo.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonInfo.setCheckable(True)
        self.toolButtonInfo.setAutoExclusive(True)
        self.toolButtonInfo.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonInfo.setObjectName("toolButtonInfo")
        self.toolButtonSettings = QtWidgets.QToolButton(self.topbar)
        self.toolButtonSettings.setGeometry(QtCore.QRect(580, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonSettings.setFont(font)
        self.toolButtonSettings.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/system/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSettings.setIcon(icon15)
        self.toolButtonSettings.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonSettings.setCheckable(True)
        self.toolButtonSettings.setAutoExclusive(True)
        self.toolButtonSettings.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonSettings.setObjectName("toolButtonSettings")
        self.toolButtonExit = QtWidgets.QToolButton(self.topbar)
        self.toolButtonExit.setGeometry(QtCore.QRect(720, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonExit.setFont(font)
        self.toolButtonExit.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/system/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExit.setIcon(icon16)
        self.toolButtonExit.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonExit.setCheckable(True)
        self.toolButtonExit.setAutoExclusive(True)
        self.toolButtonExit.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonExit.setObjectName("toolButtonExit")
        self.toolButtonCustomerVisit = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomerVisit.setEnabled(False)
        self.toolButtonCustomerVisit.setGeometry(QtCore.QRect(360, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomerVisit.setFont(font)
        self.toolButtonCustomerVisit.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/system/ordering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomerVisit.setIcon(icon17)
        self.toolButtonCustomerVisit.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomerVisit.setCheckable(True)
        self.toolButtonCustomerVisit.setAutoExclusive(True)
        self.toolButtonCustomerVisit.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomerVisit.setObjectName("toolButtonCustomerVisit")
        self.line = QtWidgets.QFrame(self.topbar)
        self.line.setGeometry(QtCore.QRect(500, 10, 3, 70))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.topbar)
        self.line_2.setGeometry(QtCore.QRect(220, 10, 3, 70))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.topbar)
        self.line_3.setGeometry(QtCore.QRect(430, 10, 3, 70))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.topbar)
        self.line_4.setGeometry(QtCore.QRect(150, 10, 3, 70))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.widgetAppPages.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.textVisitTotal, self.toolButtonReport)
        mainWindow.setTabOrder(self.toolButtonReport, self.toolButtonCustomers)
        mainWindow.setTabOrder(self.toolButtonCustomers, self.toolButtonCustomer)
        mainWindow.setTabOrder(self.toolButtonCustomer, self.toolButtonCustomerVisits)
        mainWindow.setTabOrder(self.toolButtonCustomerVisits, self.toolButtonCustomerVisit)
        mainWindow.setTabOrder(self.toolButtonCustomerVisit, self.toolButtonPricelist)
        mainWindow.setTabOrder(self.toolButtonPricelist, self.toolButtonSettings)
        mainWindow.setTabOrder(self.toolButtonSettings, self.toolButtonInfo)
        mainWindow.setTabOrder(self.toolButtonInfo, self.toolButtonExit)
        mainWindow.setTabOrder(self.toolButtonExit, self.buttonGetPricelist)
        mainWindow.setTabOrder(self.buttonGetPricelist, self.buttonGetCustomers)
        mainWindow.setTabOrder(self.buttonGetCustomers, self.buttonCreateReport)
        mainWindow.setTabOrder(self.buttonCreateReport, self.textPricelistLocalDate)
        mainWindow.setTabOrder(self.textPricelistLocalDate, self.textCustomerLocalDate)
        mainWindow.setTabOrder(self.textCustomerLocalDate, self.textWorkdate)
        mainWindow.setTabOrder(self.textWorkdate, self.textPricelistServerDate)
        mainWindow.setTabOrder(self.textPricelistServerDate, self.textCustomerServerDate)
        mainWindow.setTabOrder(self.textCustomerServerDate, self.widgetReportVisits)
        mainWindow.setTabOrder(self.widgetReportVisits, self.widgetReports)
        mainWindow.setTabOrder(self.widgetReports, self.toolButtonExportDatabase)
        mainWindow.setTabOrder(self.toolButtonExportDatabase, self.toolButtonImportDatabase)
        mainWindow.setTabOrder(self.toolButtonImportDatabase, self.toolButtonImportCsvData)
        mainWindow.setTabOrder(self.toolButtonImportCsvData, self.toolButtonDeleteSalesData)
        mainWindow.setTabOrder(self.toolButtonDeleteSalesData, self.toolButtonArchiveSettings)
        mainWindow.setTabOrder(self.toolButtonArchiveSettings, self.textAppUserMail)
        mainWindow.setTabOrder(self.textAppUserMail, self.textAppUserPass)
        mainWindow.setTabOrder(self.textAppUserPass, self.textAppUserCountry)
        mainWindow.setTabOrder(self.textAppUserCountry, self.textAppMailServer)
        mainWindow.setTabOrder(self.textAppMailServer, self.textAppMailServerPort)
        mainWindow.setTabOrder(self.textAppMailServerPort, self.textAppMailOrderTo)
        mainWindow.setTabOrder(self.textAppMailOrderTo, self.textAppDataServer)
        mainWindow.setTabOrder(self.textAppDataServer, self.checkServerData)
        mainWindow.setTabOrder(self.checkServerData, self.textExtMailServer)
        mainWindow.setTabOrder(self.textExtMailServer, self.textExtMailServerPort)
        mainWindow.setTabOrder(self.textExtMailServerPort, self.textExtMailServerUser)
        mainWindow.setTabOrder(self.textExtMailServerUser, self.textExtMailServerPass)
        mainWindow.setTabOrder(self.textExtMailServerPass, self.textVisitId)
        mainWindow.setTabOrder(self.textVisitId, self.textCustId)
        mainWindow.setTabOrder(self.textCustId, self.textCompany)
        mainWindow.setTabOrder(self.textCompany, self.textAddress1)
        mainWindow.setTabOrder(self.textAddress1, self.textAddress2)
        mainWindow.setTabOrder(self.textAddress2, self.textZipCode)
        mainWindow.setTabOrder(self.textZipCode, self.textCityName)
        mainWindow.setTabOrder(self.textCityName, self.textAccount)
        mainWindow.setTabOrder(self.textAccount, self.textPhone1)
        mainWindow.setTabOrder(self.textPhone1, self.textPhone2)
        mainWindow.setTabOrder(self.textPhone2, self.textEmail)
        mainWindow.setTabOrder(self.textEmail, self.textFactor)
        mainWindow.setTabOrder(self.textFactor, self.textCustomerNotes)
        mainWindow.setTabOrder(self.textCustomerNotes, self.buttonArchiveCustomer)
        mainWindow.setTabOrder(self.buttonArchiveCustomer, self.widgetCustomerProducts)
        mainWindow.setTabOrder(self.widgetCustomerProducts, self.widgetCustomerContacts)
        mainWindow.setTabOrder(self.widgetCustomerContacts, self.buttonCreateContact)
        mainWindow.setTabOrder(self.buttonCreateContact, self.buttonArchiveContacts)
        mainWindow.setTabOrder(self.buttonArchiveContacts, self.textCustomerName)
        mainWindow.setTabOrder(self.textCustomerName, self.textCustomerPhone1)
        mainWindow.setTabOrder(self.textCustomerPhone1, self.buttonCreateCustomer)
        mainWindow.setTabOrder(self.buttonCreateCustomer, self.widgetCustomers)
        mainWindow.setTabOrder(self.widgetCustomers, self.widgetArchivedVisits)
        mainWindow.setTabOrder(self.widgetArchivedVisits, self.buttonCreateVisit)
        mainWindow.setTabOrder(self.buttonCreateVisit, self.widgetArchivedOrderLines)
        mainWindow.setTabOrder(self.widgetArchivedOrderLines, self.textArchivedVisitNote)
        mainWindow.setTabOrder(self.textArchivedVisitNote, self.textArchivedOrderPoNumber)
        mainWindow.setTabOrder(self.textArchivedOrderPoNumber, self.textArchivedOrderSale)
        mainWindow.setTabOrder(self.textArchivedOrderSale, self.textArchivedOrderSas)
        mainWindow.setTabOrder(self.textArchivedOrderSas, self.textArchivedOrderTotal)
        mainWindow.setTabOrder(self.textArchivedOrderTotal, self.widgetPricelist)
        mainWindow.setTabOrder(self.widgetPricelist, self.toolButtonReports)
        mainWindow.setTabOrder(self.toolButtonReports, self.textVisitCompany)
        mainWindow.setTabOrder(self.textVisitCompany, self.textVisitNote)
        mainWindow.setTabOrder(self.textVisitNote, self.textVisitDate)
        mainWindow.setTabOrder(self.textVisitDate, self.textVisitBuyer)
        mainWindow.setTabOrder(self.textVisitBuyer, self.textVisitPoNumber)
        mainWindow.setTabOrder(self.textVisitPoNumber, self.textVisitProductDemo)
        mainWindow.setTabOrder(self.textVisitProductDemo, self.textVisitProductSale)
        mainWindow.setTabOrder(self.textVisitProductSale, self.textVisitOrderNote)
        mainWindow.setTabOrder(self.textVisitOrderNote, self.textVisitDelCompany)
        mainWindow.setTabOrder(self.textVisitDelCompany, self.textVisitDelAddress1)
        mainWindow.setTabOrder(self.textVisitDelAddress1, self.textVisitDelAddress2)
        mainWindow.setTabOrder(self.textVisitDelAddress2, self.textVisitDelZip)
        mainWindow.setTabOrder(self.textVisitDelZip, self.textVisitDelCity)
        mainWindow.setTabOrder(self.textVisitDelCity, self.buttonArchiveVisit)
        mainWindow.setTabOrder(self.buttonArchiveVisit, self.textVisitPcs)
        mainWindow.setTabOrder(self.textVisitPcs, self.comboOrderItem)
        mainWindow.setTabOrder(self.comboOrderItem, self.comboOrderSku)
        mainWindow.setTabOrder(self.comboOrderSku, self.textVisitSale)
        mainWindow.setTabOrder(self.textVisitSale, self.textVisitSas)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Eordre NG"))
        self.widgetCustomers.headerItem().setText(0, _translate("mainWindow", "ID"))
        self.widgetCustomers.headerItem().setText(1, _translate("mainWindow", "Konto"))
        self.widgetCustomers.headerItem().setText(2, _translate("mainWindow", "Telefon"))
        self.widgetCustomers.headerItem().setText(3, _translate("mainWindow", "Telefon"))
        self.widgetCustomers.headerItem().setText(4, _translate("mainWindow", "Firma"))
        self.widgetCustomers.headerItem().setText(5, _translate("mainWindow", "Post"))
        self.widgetCustomers.headerItem().setText(6, _translate("mainWindow", "Bynavn"))
        self.textCustomerName.setToolTip(_translate("mainWindow", "navn for ny kunde"))
        self.textCustomerName.setStatusTip(_translate("mainWindow", "Her indsættes firmanavn for kunde der skal oprettes"))
        self.textCustomerName.setPlaceholderText(_translate("mainWindow", "navn"))
        self.textCustomerPhone1.setToolTip(_translate("mainWindow", "telefon for ny kunde"))
        self.textCustomerPhone1.setStatusTip(_translate("mainWindow", "Her indsættes telefon nummer for kunde der skal oprettes\n"
"                                                "))
        self.textCustomerPhone1.setPlaceholderText(_translate("mainWindow", "telefon"))
        self.buttonCreateCustomer.setToolTip(_translate("mainWindow", "Opret ny kunde"))
        self.buttonCreateCustomer.setStatusTip(_translate("mainWindow", "Udfyld felterne og tryk her for at oprette firma"))
        self.buttonCreateCustomer.setText(_translate("mainWindow", "Opret kunde"))
        self.textFactor.setToolTip(_translate("mainWindow", "Faktor"))
        self.textFactor.setStatusTip(_translate("mainWindow", "Ved salg bliver liste priser ganget med\n"
"                                                                        faktor\n"
"                                                                    "))
        self.textFactor.setPlaceholderText(_translate("mainWindow", "faktor"))
        self.textAddress2.setToolTip(_translate("mainWindow", "Udvidet adresse"))
        self.textAddress2.setStatusTip(_translate("mainWindow", "Dette felt er udvidet adresse"))
        self.textAddress2.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone1.setToolTip(_translate("mainWindow", "Primær telefon"))
        self.textPhone1.setStatusTip(_translate("mainWindow", "Dette felt er primær telefon til kunde\n"
"                                                                    "))
        self.textPhone1.setPlaceholderText(_translate("mainWindow", "primær telefon"))
        self.textEmail.setToolTip(_translate("mainWindow", "Epost adresse"))
        self.textEmail.setStatusTip(_translate("mainWindow", "Dette felt er epost adresse for kunde\n"
"                                                                    "))
        self.textEmail.setPlaceholderText(_translate("mainWindow", "epost adresse"))
        self.textAddress1.setToolTip(_translate("mainWindow", "Kundens adresse"))
        self.textAddress1.setStatusTip(_translate("mainWindow", "Dette felt er kunde adresse"))
        self.textAddress1.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone2.setToolTip(_translate("mainWindow", "Anden telefon"))
        self.textPhone2.setStatusTip(_translate("mainWindow", "Dette felt er mobil eller anden telefon til\n"
"                                                                        kunde\n"
"                                                                    "))
        self.textPhone2.setPlaceholderText(_translate("mainWindow", "mobil telefon"))
        self.textCompany.setToolTip(_translate("mainWindow", "Firmanavn"))
        self.textCompany.setStatusTip(_translate("mainWindow", "Dette felt er kunde navn"))
        self.textCompany.setPlaceholderText(_translate("mainWindow", "firma navn"))
        self.textAccount.setToolTip(_translate("mainWindow", "Kundekonto"))
        self.textAccount.setStatusTip(_translate("mainWindow", "Dette felt er konto for kunde"))
        self.textAccount.setPlaceholderText(_translate("mainWindow", "konto"))
        self.textCityName.setToolTip(_translate("mainWindow", "Bynavn"))
        self.textCityName.setStatusTip(_translate("mainWindow", "Dette felt er bynavn for kunde"))
        self.textCityName.setPlaceholderText(_translate("mainWindow", "by navn"))
        self.textZipCode.setToolTip(_translate("mainWindow", "Postnummer"))
        self.textZipCode.setStatusTip(_translate("mainWindow", "Dette felt er postnummer for kunde"))
        self.textZipCode.setPlaceholderText(_translate("mainWindow", "post nummer"))
        self.widgetCustomerContacts.headerItem().setText(0, _translate("mainWindow", "Navn"))
        self.widgetCustomerContacts.headerItem().setText(1, _translate("mainWindow", "Telefon"))
        self.widgetCustomerContacts.headerItem().setText(2, _translate("mainWindow", "Afdeling"))
        self.widgetCustomerContacts.headerItem().setText(3, _translate("mainWindow", "Email"))
        self.widgetCustomerContacts.headerItem().setText(4, _translate("mainWindow", "Info"))
        self.buttonArchiveContacts.setText(_translate("mainWindow", "Arkiver kontakter"))
        self.buttonCreateContact.setText(_translate("mainWindow", "Tilføj kontakt ..."))
        self.buttonArchiveCustomer.setToolTip(_translate("mainWindow", "Arkiver ændringer"))
        self.buttonArchiveCustomer.setStatusTip(_translate("mainWindow", "Tryk her for at gemme rettelser i\n"
"                                                                        databasen\n"
"                                                                    "))
        self.buttonArchiveCustomer.setText(_translate("mainWindow", "Arkiver kunde"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Varenr"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Total"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Bestil"))
        self.widgetArchivedVisits.headerItem().setText(0, _translate("mainWindow", "Id"))
        self.widgetArchivedVisits.headerItem().setText(1, _translate("mainWindow", "Dato"))
        self.widgetArchivedVisits.headerItem().setText(2, _translate("mainWindow", "Navn"))
        self.widgetArchivedVisits.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.widgetArchivedVisits.headerItem().setText(4, _translate("mainWindow", "Salg"))
        self.widgetArchivedVisits.headerItem().setText(5, _translate("mainWindow", "Ordre note"))
        self.widgetArchivedOrderLines.headerItem().setText(0, _translate("mainWindow", "*"))
        self.widgetArchivedOrderLines.headerItem().setText(1, _translate("mainWindow", "Ant"))
        self.widgetArchivedOrderLines.headerItem().setText(2, _translate("mainWindow", "SKU"))
        self.widgetArchivedOrderLines.headerItem().setText(3, _translate("mainWindow", "Vare"))
        self.widgetArchivedOrderLines.headerItem().setText(4, _translate("mainWindow", "Pris"))
        self.widgetArchivedOrderLines.headerItem().setText(5, _translate("mainWindow", "%"))
        self.widgetArchivedOrderLines.headerItem().setText(6, _translate("mainWindow", "Linje note"))
        self.labelArchivedSend.setText(_translate("mainWindow", "Afsl."))
        self.labelArchivedOrderSale.setText(_translate("mainWindow", "Salg"))
        self.labelArchivedSasAmount.setText(_translate("mainWindow", "SAS"))
        self.labelArchivedOrderTotal.setText(_translate("mainWindow", "Total"))
        self.labelArchivedPurchaseOrder.setText(_translate("mainWindow", "Rekv."))
        self.labelArchivedApproved.setText(_translate("mainWindow", "Godk."))
        self.textCustomerNameCreateVisit.setToolTip(_translate("mainWindow", "navn for ny kunde"))
        self.textCustomerNameCreateVisit.setStatusTip(_translate("mainWindow", "Her indsættes firmanavn for kunde der skal oprettes"))
        self.textCustomerNameCreateVisit.setPlaceholderText(_translate("mainWindow", "navn"))
        self.buttonCreateVisit.setText(_translate("mainWindow", "Tilføj besøg ..."))
        self.widgetPricelist.setSortingEnabled(True)
        self.widgetPricelist.headerItem().setText(1, _translate("mainWindow", "Varenr."))
        self.widgetPricelist.headerItem().setText(2, _translate("mainWindow", "Varetekst"))
        self.widgetPricelist.headerItem().setText(3, _translate("mainWindow", "1 stk"))
        self.widgetPricelist.headerItem().setText(4, _translate("mainWindow", "2 stk"))
        self.widgetPricelist.headerItem().setText(5, _translate("mainWindow", "4 stk"))
        self.widgetPricelist.headerItem().setText(6, _translate("mainWindow", "6 stk"))
        self.widgetPricelist.headerItem().setText(7, _translate("mainWindow", "8 stk"))
        self.widgetPricelist.headerItem().setText(8, _translate("mainWindow", "12 stk"))
        self.widgetPricelist.headerItem().setText(9, _translate("mainWindow", "24 stk"))
        self.widgetPricelist.headerItem().setText(10, _translate("mainWindow", "48 stk"))
        self.widgetPricelist.headerItem().setText(11, _translate("mainWindow", "96 stk"))
        self.widgetPricelist.headerItem().setText(12, _translate("mainWindow", "Netto"))
        __sortingEnabled = self.widgetPricelist.isSortingEnabled()
        self.widgetPricelist.setSortingEnabled(False)
        self.widgetPricelist.topLevelItem(0).setText(0, _translate("mainWindow", "sa"))
        self.widgetPricelist.topLevelItem(0).setText(1, _translate("mainWindow", "01,0108"))
        self.widgetPricelist.topLevelItem(0).setText(2, _translate("mainWindow", "Lim-Spray"))
        self.widgetPricelist.topLevelItem(0).setText(3, _translate("mainWindow", "123"))
        self.widgetPricelist.topLevelItem(0).setText(8, _translate("mainWindow", "108"))
        self.widgetPricelist.topLevelItem(0).setText(9, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(0).setText(12, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(1).setText(0, _translate("mainWindow", "qba"))
        self.widgetPricelist.topLevelItem(1).setText(1, _translate("mainWindow", "01,0136"))
        self.widgetPricelist.topLevelItem(1).setText(2, _translate("mainWindow", "Activator Quick Bond"))
        self.widgetPricelist.topLevelItem(1).setText(3, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(6, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(8, _translate("mainWindow", "169"))
        self.widgetPricelist.topLevelItem(1).setText(12, _translate("mainWindow", "161"))
        self.widgetPricelist.setSortingEnabled(__sortingEnabled)
        self.textPricelistLocalDate.setToolTip(_translate("mainWindow", "Prisliste synkroniseret"))
        self.textPricelistLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af prisliste"))
        self.textPricelistLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonGetPricelist.setText(_translate("mainWindow", "Opdater prisliste"))
        self.textPricelistServerDate.setToolTip(_translate("mainWindow", "Tilgængelig prisliste"))
        self.textPricelistServerDate.setStatusTip(_translate("mainWindow", "Dette er datoen for serverens prisliste"))
        self.textPricelistServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonGetCustomers.setText(_translate("mainWindow", "Opdater kundeliste"))
        self.textCustomerLocalDate.setToolTip(_translate("mainWindow", "Kundeliste synkroniseret"))
        self.textCustomerLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af kundeliste"))
        self.textCustomerLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.textCustomerServerDate.setToolTip(_translate("mainWindow", "Tilgængelig kundeliste"))
        self.textCustomerServerDate.setStatusTip(_translate("mainWindow", "Dette datoen for serverens kundeliste"))
        self.textCustomerServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonCreateReport.setToolTip(_translate("mainWindow", "Opret dagsrapport"))
        self.buttonCreateReport.setStatusTip(_translate("mainWindow", "Her opretter du en dagsrapport datoen i feltet"))
        self.buttonCreateReport.setText(_translate("mainWindow", "Sæt Arbejdsdato"))
        self.textWorkdate.setToolTip(_translate("mainWindow", "Arbejdsdato"))
        self.textWorkdate.setStatusTip(_translate("mainWindow", "Dette er systemets arbejdsdato"))
        self.textWorkdate.setPlaceholderText(_translate("mainWindow", "arbejdsdato"))
        self.labelLastUpdated.setText(_translate("mainWindow", "Sidst opdateret"))
        self.labelAvailable.setText(_translate("mainWindow", "Server liste dato"))
        self.widgetReportVisits.headerItem().setText(0, _translate("mainWindow", "Firma"))
        self.widgetReportVisits.headerItem().setText(1, _translate("mainWindow", "Demo"))
        self.widgetReportVisits.headerItem().setText(2, _translate("mainWindow", "Salg"))
        self.widgetReportVisits.headerItem().setText(3, _translate("mainWindow", "Total"))
        self.widgetReports.headerItem().setText(0, _translate("mainWindow", "ID"))
        self.widgetReports.headerItem().setText(2, _translate("mainWindow", "Besøg"))
        self.widgetReports.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.widgetReports.headerItem().setText(4, _translate("mainWindow", "Salg"))
        self.widgetReports.headerItem().setText(5, _translate("mainWindow", "Oms"))
        self.widgetReports.headerItem().setText(6, _translate("mainWindow", "Km"))
        self.widgetReports.headerItem().setText(7, _translate("mainWindow", "Supervisor"))
        self.groupSalesPerson.setTitle(_translate("mainWindow", "Sælger"))
        self.textAppUserCountry.setPlaceholderText(_translate("mainWindow", "landkode: dk"))
        self.textAppUserPass.setPlaceholderText(_translate("mainWindow", "din adgangs frase"))
        self.textAppUserMail.setPlaceholderText(_translate("mainWindow", "brugers mail adresse: email@domæne.tld"))
        self.groupInternalServers.setTitle(_translate("mainWindow", "Intern mail og data server"))
        self.checkServerData.setText(_translate("mainWindow", "Ved programstart kontroller server data"))
        self.textAppDataServer.setPlaceholderText(_translate("mainWindow", "webserver: http://localhost:8080"))
        self.textAppMailOrderTo.setPlaceholderText(_translate("mainWindow", "modtager email: email@domain.tld"))
        self.textAppMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textAppMailServer.setPlaceholderText(_translate("mainWindow", "post server: mail.domain.tld"))
        self.groupExternalServer.setTitle(_translate("mainWindow", "Ekstern mailserver"))
        self.textExtMailServerUser.setPlaceholderText(_translate("mainWindow", "post server: brugernavn"))
        self.textExtMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textExtMailServerPass.setPlaceholderText(_translate("mainWindow", "post server: adgangskode"))
        self.textExtMailServer.setPlaceholderText(_translate("mainWindow", "post server: server.domain.tld"))
        self.toolButtonDeleteSalesData.setText(_translate("mainWindow", "SLET"))
        self.toolButtonImportDatabase.setText(_translate("mainWindow", "Import"))
        self.toolButtonExportDatabase.setText(_translate("mainWindow", "Eksport"))
        self.toolButtonImportCsvData.setText(_translate("mainWindow", "CSV"))
        self.toolButtonArchiveSettings.setText(_translate("mainWindow", "Gem"))
        self.labelAbout.setText(_translate("mainWindow", "about page"))
        self.groupOrderHead.setTitle(_translate("mainWindow", "Ordrehoved"))
        self.textVisitProductDemo.setPlaceholderText(_translate("mainWindow", "Produkt demo"))
        self.textVisitDate.setPlaceholderText(_translate("mainWindow", "Ordre dato"))
        self.textVisitDelAddress2.setPlaceholderText(_translate("mainWindow", "Lev. adresse 2"))
        self.textVisitPoNumber.setPlaceholderText(_translate("mainWindow", "Rekvisition"))
        self.textVisitDelAddress1.setPlaceholderText(_translate("mainWindow", "Lev. adresse 1"))
        self.textVisitDelCompany.setPlaceholderText(_translate("mainWindow", "Lev. til"))
        self.textVisitProductSale.setPlaceholderText(_translate("mainWindow", "Produkt salg"))
        self.textVisitDelCity.setPlaceholderText(_translate("mainWindow", "Lev. bynavn"))
        self.textVisitDelZip.setPlaceholderText(_translate("mainWindow", "Lev. postnummer"))
        self.textVisitBuyer.setPlaceholderText(_translate("mainWindow", "Indkøber"))
        self.textVisitOrderNote.setPlaceholderText(_translate("mainWindow", "Ordre note"))
        self.groupVisitHead.setTitle(_translate("mainWindow", "Besøg"))
        self.textVisitNote.setPlaceholderText(_translate("mainWindow", "Besøgs note"))
        self.buttonArchiveVisit.setText(_translate("mainWindow", "Arkiver"))
        self.textVisitId.setPlaceholderText(_translate("mainWindow", "visitid"))
        self.textCustId.setPlaceholderText(_translate("mainWindow", "custid"))
        self.label.setText(_translate("mainWindow", "Produkt valg"))
        self.textVisitPcs.setPlaceholderText(_translate("mainWindow", "antal"))
        self.labelTotal.setText(_translate("mainWindow", "Total"))
        self.labelSas.setText(_translate("mainWindow", "SAS"))
        self.labelSale.setText(_translate("mainWindow", "Salg"))
        self.groupBoxDemo.setTitle(_translate("mainWindow", "Demo"))
        self.widgetTableDemo.setToolTip(_translate("mainWindow", "Demo "))
        item = self.widgetTableDemo.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "*"))
        item = self.widgetTableDemo.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.widgetTableDemo.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Nummer"))
        self.toolButtonAddDemo.setText(_translate("mainWindow", "..."))
        self.toolButtonRemoveDemo.setText(_translate("mainWindow", "..."))
        self.groupBoxSale.setTitle(_translate("mainWindow", "Salg"))
        self.widgetTableSale.setToolTip(_translate("mainWindow", "Demo "))
        item = self.widgetTableSale.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "*"))
        item = self.widgetTableSale.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Ant"))
        item = self.widgetTableSale.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.widgetTableSale.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Nummer"))
        item = self.widgetTableSale.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Pris"))
        item = self.widgetTableSale.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Rabat"))
        item = self.widgetTableSale.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Sas"))
        self.toolButtonRemoveSale.setText(_translate("mainWindow", "..."))
        self.toolButtonAddSale.setText(_translate("mainWindow", "..."))
        self.toolButtonReport.setToolTip(_translate("mainWindow", "Dagens rapport"))
        self.toolButtonCustomers.setToolTip(_translate("mainWindow", "Kunde liste"))
        self.toolButtonCustomer.setToolTip(_translate("mainWindow", "Kunde"))
        self.toolButtonCustomerVisits.setToolTip(_translate("mainWindow", "Kundebesøg"))
        self.toolButtonPricelist.setToolTip(_translate("mainWindow", "Prisliste"))
        self.toolButtonReports.setToolTip(_translate("mainWindow", "Rapporter"))
        self.toolButtonInfo.setToolTip(_translate("mainWindow", "Info"))
        self.toolButtonSettings.setToolTip(_translate("mainWindow", "Indstillinger"))
        self.toolButtonExit.setToolTip(_translate("mainWindow", "Afslut"))
        self.toolButtonCustomerVisit.setToolTip(_translate("mainWindow", "Åben ordre/besøg"))

from . import system_rc
