# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(953, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("")
        mainWindow.setIconSize(QtCore.QSize(48, 48))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.widgetAppPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.widgetAppPages.setGeometry(QtCore.QRect(0, 90, 800, 560))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetAppPages.setFont(font)
        self.widgetAppPages.setObjectName("widgetAppPages")
        self.widgetPageCustomers = QtWidgets.QWidget()
        self.widgetPageCustomers.setObjectName("widgetPageCustomers")
        self.widgetAppCustomers = QtWidgets.QTreeWidget(self.widgetPageCustomers)
        self.widgetAppCustomers.setGeometry(QtCore.QRect(10, 10, 780, 360))
        self.widgetAppCustomers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetAppCustomers.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetAppCustomers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetAppCustomers.setAlternatingRowColors(True)
        self.widgetAppCustomers.setIndentation(20)
        self.widgetAppCustomers.setRootIsDecorated(False)
        self.widgetAppCustomers.setItemsExpandable(False)
        self.widgetAppCustomers.setExpandsOnDoubleClick(False)
        self.widgetAppCustomers.setColumnCount(6)
        self.widgetAppCustomers.setObjectName("widgetAppCustomers")
        self.widgetAppCustomers.header().setDefaultSectionSize(80)
        self.layoutWidget_4 = QtWidgets.QWidget(self.widgetPageCustomers)
        self.layoutWidget_4.setGeometry(QtCore.QRect(220, 380, 271, 86))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.widgetAppCreateCustomer = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.widgetAppCreateCustomer.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCreateCustomer.setObjectName("widgetAppCreateCustomer")
        self.textCustomerName = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerName.setFont(font)
        self.textCustomerName.setObjectName("textCustomerName")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerName, 0, 0, 1, 1)
        self.textCustomerPhone1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerPhone1.setFont(font)
        self.textCustomerPhone1.setObjectName("textCustomerPhone1")
        self.widgetAppCreateCustomer.addWidget(self.textCustomerPhone1, 1, 0, 1, 1)
        self.buttonCreateCustomer = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateCustomer.setFont(font)
        self.buttonCreateCustomer.setObjectName("buttonCreateCustomer")
        self.widgetAppCreateCustomer.addWidget(self.buttonCreateCustomer, 2, 0, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageCustomers)
        self.widgetPageCustomer = QtWidgets.QWidget()
        self.widgetPageCustomer.setObjectName("widgetPageCustomer")
        self.layoutWidget = QtWidgets.QWidget(self.widgetPageCustomer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 530, 190))
        self.layoutWidget.setObjectName("layoutWidget")
        self.widgetAppCustomer = QtWidgets.QGridLayout(self.layoutWidget)
        self.widgetAppCustomer.setContentsMargins(0, 0, 0, 0)
        self.widgetAppCustomer.setObjectName("widgetAppCustomer")
        self.textFactor = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textFactor.setFont(font)
        self.textFactor.setObjectName("textFactor")
        self.widgetAppCustomer.addWidget(self.textFactor, 4, 1, 1, 1)
        self.textAddress2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress2.setFont(font)
        self.textAddress2.setObjectName("textAddress2")
        self.widgetAppCustomer.addWidget(self.textAddress2, 2, 0, 1, 1)
        self.textPhone1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone1.setFont(font)
        self.textPhone1.setObjectName("textPhone1")
        self.widgetAppCustomer.addWidget(self.textPhone1, 1, 1, 1, 1)
        self.textEmail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEmail.setFont(font)
        self.textEmail.setObjectName("textEmail")
        self.widgetAppCustomer.addWidget(self.textEmail, 3, 1, 1, 1)
        self.textAddress1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textAddress1.setFont(font)
        self.textAddress1.setObjectName("textAddress1")
        self.widgetAppCustomer.addWidget(self.textAddress1, 1, 0, 1, 1)
        self.textPhone2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPhone2.setFont(font)
        self.textPhone2.setObjectName("textPhone2")
        self.widgetAppCustomer.addWidget(self.textPhone2, 2, 1, 1, 1)
        self.textCompany = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCompany.setFont(font)
        self.textCompany.setObjectName("textCompany")
        self.widgetAppCustomer.addWidget(self.textCompany, 0, 0, 1, 1)
        self.textAccount = QtWidgets.QLineEdit(self.layoutWidget)
        self.textAccount.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textAccount.setFont(font)
        self.textAccount.setReadOnly(True)
        self.textAccount.setObjectName("textAccount")
        self.widgetAppCustomer.addWidget(self.textAccount, 0, 1, 1, 1)
        self.textCityName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCityName.setFont(font)
        self.textCityName.setObjectName("textCityName")
        self.widgetAppCustomer.addWidget(self.textCityName, 4, 0, 1, 1)
        self.textZipCode = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textZipCode.setFont(font)
        self.textZipCode.setObjectName("textZipCode")
        self.widgetAppCustomer.addWidget(self.textZipCode, 3, 0, 1, 1)
        self.widgetCustomerContacts = QtWidgets.QTreeWidget(self.widgetPageCustomer)
        self.widgetCustomerContacts.setGeometry(QtCore.QRect(10, 390, 530, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetCustomerContacts.sizePolicy().hasHeightForWidth())
        self.widgetCustomerContacts.setSizePolicy(sizePolicy)
        self.widgetCustomerContacts.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetCustomerContacts.setIndentation(0)
        self.widgetCustomerContacts.setRootIsDecorated(False)
        self.widgetCustomerContacts.setItemsExpandable(False)
        self.widgetCustomerContacts.setExpandsOnDoubleClick(False)
        self.widgetCustomerContacts.setObjectName("widgetCustomerContacts")
        self.textCustomerNotes = QtWidgets.QTextEdit(self.widgetPageCustomer)
        self.textCustomerNotes.setGeometry(QtCore.QRect(550, 10, 240, 101))
        self.textCustomerNotes.setObjectName("textCustomerNotes")
        self.buttonArchiveContacts = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveContacts.setGeometry(QtCore.QRect(560, 470, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveContacts.setFont(font)
        self.buttonArchiveContacts.setObjectName("buttonArchiveContacts")
        self.buttonCreateContact = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonCreateContact.setGeometry(QtCore.QRect(560, 393, 210, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateContact.setFont(font)
        self.buttonCreateContact.setObjectName("buttonCreateContact")
        self.buttonArchiveCustomer = QtWidgets.QPushButton(self.widgetPageCustomer)
        self.buttonArchiveCustomer.setGeometry(QtCore.QRect(560, 170, 220, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveCustomer.setFont(font)
        self.buttonArchiveCustomer.setObjectName("buttonArchiveCustomer")
        self.widgetCustomerProducts = QtWidgets.QTableWidget(self.widgetPageCustomer)
        self.widgetCustomerProducts.setGeometry(QtCore.QRect(10, 210, 530, 170))
        self.widgetCustomerProducts.setObjectName("widgetCustomerProducts")
        self.widgetCustomerProducts.setColumnCount(4)
        self.widgetCustomerProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetCustomerProducts.setHorizontalHeaderItem(3, item)
        self.widgetAppPages.addWidget(self.widgetPageCustomer)
        self.widgetPageCustomerVisits = QtWidgets.QWidget()
        self.widgetPageCustomerVisits.setObjectName("widgetPageCustomerVisits")
        self.widgetArchivedVisits = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetArchivedVisits.setGeometry(QtCore.QRect(10, 10, 640, 170))
        self.widgetArchivedVisits.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetArchivedVisits.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetArchivedVisits.setAlternatingRowColors(True)
        self.widgetArchivedVisits.setIndentation(0)
        self.widgetArchivedVisits.setRootIsDecorated(False)
        self.widgetArchivedVisits.setItemsExpandable(False)
        self.widgetArchivedVisits.setExpandsOnDoubleClick(False)
        self.widgetArchivedVisits.setObjectName("widgetArchivedVisits")
        self.widgetArchivedOrderLines = QtWidgets.QTreeWidget(self.widgetPageCustomerVisits)
        self.widgetArchivedOrderLines.setGeometry(QtCore.QRect(10, 185, 780, 140))
        self.widgetArchivedOrderLines.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetArchivedOrderLines.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetArchivedOrderLines.setAlternatingRowColors(True)
        self.widgetArchivedOrderLines.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetArchivedOrderLines.setIndentation(0)
        self.widgetArchivedOrderLines.setRootIsDecorated(False)
        self.widgetArchivedOrderLines.setItemsExpandable(False)
        self.widgetArchivedOrderLines.setObjectName("widgetArchivedOrderLines")
        self.layoutWidget1 = QtWidgets.QWidget(self.widgetPageCustomerVisits)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 330, 220, 160))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.widgetArchivedOrder = QtWidgets.QGridLayout(self.layoutWidget1)
        self.widgetArchivedOrder.setContentsMargins(0, 0, 0, 0)
        self.widgetArchivedOrder.setObjectName("widgetArchivedOrder")
        self.labelArchivedSend = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedSend.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedSend.setObjectName("labelArchivedSend")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSend, 4, 2, 1, 1)
        self.labelArchivedSendText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchivedSendText.sizePolicy().hasHeightForWidth())
        self.labelArchivedSendText.setSizePolicy(sizePolicy)
        self.labelArchivedSendText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchivedSendText.setFont(font)
        self.labelArchivedSendText.setText("")
        self.labelArchivedSendText.setObjectName("labelArchivedSendText")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSendText, 4, 3, 1, 1)
        self.labelArchivedOrderSale = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedOrderSale.setObjectName("labelArchivedOrderSale")
        self.widgetArchivedOrder.addWidget(self.labelArchivedOrderSale, 1, 2, 1, 1)
        self.textArchivedOrderSale = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderSale.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderSale.setSizePolicy(sizePolicy)
        self.textArchivedOrderSale.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderSale.setReadOnly(True)
        self.textArchivedOrderSale.setObjectName("textArchivedOrderSale")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderSale, 1, 3, 1, 1)
        self.labelArchivedSasAmount = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedSasAmount.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedSasAmount.setObjectName("labelArchivedSasAmount")
        self.widgetArchivedOrder.addWidget(self.labelArchivedSasAmount, 2, 2, 1, 1)
        self.labelArchivedOrderTotal = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedOrderTotal.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedOrderTotal.setObjectName("labelArchivedOrderTotal")
        self.widgetArchivedOrder.addWidget(self.labelArchivedOrderTotal, 3, 2, 1, 1)
        self.textArchivedOrderSas = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderSas.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderSas.setSizePolicy(sizePolicy)
        self.textArchivedOrderSas.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderSas.setReadOnly(True)
        self.textArchivedOrderSas.setObjectName("textArchivedOrderSas")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderSas, 2, 3, 1, 1)
        self.textArchivedOrderTotal = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderTotal.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderTotal.setSizePolicy(sizePolicy)
        self.textArchivedOrderTotal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderTotal.setReadOnly(True)
        self.textArchivedOrderTotal.setObjectName("textArchivedOrderTotal")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderTotal, 3, 3, 1, 1)
        self.textArchivedOrderPoNumber = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textArchivedOrderPoNumber.sizePolicy().hasHeightForWidth())
        self.textArchivedOrderPoNumber.setSizePolicy(sizePolicy)
        self.textArchivedOrderPoNumber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textArchivedOrderPoNumber.setReadOnly(True)
        self.textArchivedOrderPoNumber.setObjectName("textArchivedOrderPoNumber")
        self.widgetArchivedOrder.addWidget(self.textArchivedOrderPoNumber, 0, 3, 1, 1)
        self.labelArchivedPurchaseOrder = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedPurchaseOrder.setMaximumSize(QtCore.QSize(16777215, 16))
        self.labelArchivedPurchaseOrder.setObjectName("labelArchivedPurchaseOrder")
        self.widgetArchivedOrder.addWidget(self.labelArchivedPurchaseOrder, 0, 2, 1, 1)
        self.labelArchivedApproved = QtWidgets.QLabel(self.layoutWidget1)
        self.labelArchivedApproved.setObjectName("labelArchivedApproved")
        self.widgetArchivedOrder.addWidget(self.labelArchivedApproved, 5, 2, 1, 1)
        self.labelArchivedApprovedText = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArchivedApprovedText.sizePolicy().hasHeightForWidth())
        self.labelArchivedApprovedText.setSizePolicy(sizePolicy)
        self.labelArchivedApprovedText.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelArchivedApprovedText.setFont(font)
        self.labelArchivedApprovedText.setText("")
        self.labelArchivedApprovedText.setObjectName("labelArchivedApprovedText")
        self.widgetArchivedOrder.addWidget(self.labelArchivedApprovedText, 5, 3, 1, 1)
        self.buttonCreateVisit = QtWidgets.QPushButton(self.widgetPageCustomerVisits)
        self.buttonCreateVisit.setGeometry(QtCore.QRect(670, 20, 120, 27))
        self.buttonCreateVisit.setObjectName("buttonCreateVisit")
        self.textArchivedVisitNote = QtWidgets.QTextEdit(self.widgetPageCustomerVisits)
        self.textArchivedVisitNote.setGeometry(QtCore.QRect(10, 330, 550, 160))
        self.textArchivedVisitNote.setReadOnly(True)
        self.textArchivedVisitNote.setObjectName("textArchivedVisitNote")
        self.widgetAppPages.addWidget(self.widgetPageCustomerVisits)
        self.widgetPagePricelist = QtWidgets.QWidget()
        self.widgetPagePricelist.setObjectName("widgetPagePricelist")
        self.widgetPricelist = QtWidgets.QTreeWidget(self.widgetPagePricelist)
        self.widgetPricelist.setGeometry(QtCore.QRect(10, 10, 780, 330))
        self.widgetPricelist.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.widgetPricelist.setObjectName("widgetPricelist")
        self.widgetPricelist.headerItem().setText(0, "Produkt")
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        item_0 = QtWidgets.QTreeWidgetItem(self.widgetPricelist)
        self.widgetAppPages.addWidget(self.widgetPagePricelist)
        self.widgetPageReport = QtWidgets.QWidget()
        self.widgetPageReport.setObjectName("widgetPageReport")
        self.layoutWidget_2 = QtWidgets.QWidget(self.widgetPageReport)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 293, 116))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.widgetAppLastUpdate = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.widgetAppLastUpdate.setContentsMargins(0, 0, 0, 0)
        self.widgetAppLastUpdate.setObjectName("widgetAppLastUpdate")
        self.textPricelistLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistLocalDate.setFont(font)
        self.textPricelistLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistLocalDate.setReadOnly(True)
        self.textPricelistLocalDate.setObjectName("textPricelistLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistLocalDate, 2, 2, 1, 1)
        self.buttonGetPricelist = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetPricelist.setObjectName("buttonGetPricelist")
        self.widgetAppLastUpdate.addWidget(self.buttonGetPricelist, 1, 2, 1, 1)
        self.textPricelistServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textPricelistServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textPricelistServerDate.setFont(font)
        self.textPricelistServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textPricelistServerDate.setReadOnly(True)
        self.textPricelistServerDate.setObjectName("textPricelistServerDate")
        self.widgetAppLastUpdate.addWidget(self.textPricelistServerDate, 3, 2, 1, 1)
        self.buttonGetCustomers = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonGetCustomers.setObjectName("buttonGetCustomers")
        self.widgetAppLastUpdate.addWidget(self.buttonGetCustomers, 1, 3, 1, 1)
        self.textCustomerLocalDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerLocalDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerLocalDate.setFont(font)
        self.textCustomerLocalDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerLocalDate.setReadOnly(True)
        self.textCustomerLocalDate.setObjectName("textCustomerLocalDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerLocalDate, 2, 3, 1, 1)
        self.textCustomerServerDate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textCustomerServerDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textCustomerServerDate.setFont(font)
        self.textCustomerServerDate.setAlignment(QtCore.Qt.AlignCenter)
        self.textCustomerServerDate.setReadOnly(True)
        self.textCustomerServerDate.setObjectName("textCustomerServerDate")
        self.widgetAppLastUpdate.addWidget(self.textCustomerServerDate, 3, 3, 1, 1)
        self.buttonCreateReport = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonCreateReport.setFont(font)
        self.buttonCreateReport.setObjectName("buttonCreateReport")
        self.widgetAppLastUpdate.addWidget(self.buttonCreateReport, 1, 4, 1, 1)
        self.textWorkdate = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.textWorkdate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textWorkdate.setFont(font)
        self.textWorkdate.setAlignment(QtCore.Qt.AlignCenter)
        self.textWorkdate.setReadOnly(False)
        self.textWorkdate.setObjectName("textWorkdate")
        self.widgetAppLastUpdate.addWidget(self.textWorkdate, 2, 4, 1, 1)
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.widgetPageReport)
        self.treeWidget_2.setGeometry(QtCore.QRect(340, 10, 451, 491))
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.widgetAppPages.addWidget(self.widgetPageReport)
        self.widgetPageReports = QtWidgets.QWidget()
        self.widgetPageReports.setObjectName("widgetPageReports")
        self.treeWidget = QtWidgets.QTreeWidget(self.widgetPageReports)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 780, 430))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Dato")
        self.widgetAppPages.addWidget(self.widgetPageReports)
        self.widgetPageSettings = QtWidgets.QWidget()
        self.widgetPageSettings.setObjectName("widgetPageSettings")
        self.groupSalesPerson = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupSalesPerson.setGeometry(QtCore.QRect(10, 100, 320, 150))
        self.groupSalesPerson.setObjectName("groupSalesPerson")
        self.textAppUserCountry = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserCountry.setGeometry(QtCore.QRect(10, 110, 300, 26))
        self.textAppUserCountry.setMaxLength(2)
        self.textAppUserCountry.setObjectName("textAppUserCountry")
        self.textAppUserPass = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserPass.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppUserPass.setInputMask("")
        self.textAppUserPass.setMaxLength(100)
        self.textAppUserPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textAppUserPass.setObjectName("textAppUserPass")
        self.textAppUserMail = QtWidgets.QLineEdit(self.groupSalesPerson)
        self.textAppUserMail.setGeometry(QtCore.QRect(10, 30, 300, 28))
        self.textAppUserMail.setText("")
        self.textAppUserMail.setMaxLength(100)
        self.textAppUserMail.setFrame(True)
        self.textAppUserMail.setObjectName("textAppUserMail")
        self.groupInternalServers = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupInternalServers.setGeometry(QtCore.QRect(420, 100, 320, 180))
        self.groupInternalServers.setObjectName("groupInternalServers")
        self.checkServerData = QtWidgets.QCheckBox(self.groupInternalServers)
        self.checkServerData.setGeometry(QtCore.QRect(10, 150, 300, 22))
        self.checkServerData.setObjectName("checkServerData")
        self.textAppDataServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppDataServer.setGeometry(QtCore.QRect(10, 110, 299, 28))
        self.textAppDataServer.setMaxLength(100)
        self.textAppDataServer.setObjectName("textAppDataServer")
        self.textAppMailOrderTo = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailOrderTo.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textAppMailOrderTo.setText("")
        self.textAppMailOrderTo.setMaxLength(100)
        self.textAppMailOrderTo.setObjectName("textAppMailOrderTo")
        self.textAppMailServerPort = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textAppMailServerPort.setMaxLength(3)
        self.textAppMailServerPort.setObjectName("textAppMailServerPort")
        self.textAppMailServer = QtWidgets.QLineEdit(self.groupInternalServers)
        self.textAppMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textAppMailServer.setText("")
        self.textAppMailServer.setMaxLength(100)
        self.textAppMailServer.setObjectName("textAppMailServer")
        self.groupExternalServer = QtWidgets.QGroupBox(self.widgetPageSettings)
        self.groupExternalServer.setGeometry(QtCore.QRect(420, 330, 320, 150))
        self.groupExternalServer.setObjectName("groupExternalServer")
        self.textExtMailServerUser = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerUser.setGeometry(QtCore.QRect(10, 70, 300, 28))
        self.textExtMailServerUser.setInputMask("")
        self.textExtMailServerUser.setText("")
        self.textExtMailServerUser.setMaxLength(100)
        self.textExtMailServerUser.setObjectName("textExtMailServerUser")
        self.textExtMailServerPort = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPort.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.textExtMailServerPort.setMaxLength(3)
        self.textExtMailServerPort.setObjectName("textExtMailServerPort")
        self.textExtMailServerPass = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServerPass.setGeometry(QtCore.QRect(10, 110, 300, 28))
        self.textExtMailServerPass.setText("")
        self.textExtMailServerPass.setMaxLength(100)
        self.textExtMailServerPass.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.textExtMailServerPass.setObjectName("textExtMailServerPass")
        self.textExtMailServer = QtWidgets.QLineEdit(self.groupExternalServer)
        self.textExtMailServer.setGeometry(QtCore.QRect(10, 30, 200, 28))
        self.textExtMailServer.setMaxLength(100)
        self.textExtMailServer.setObjectName("textExtMailServer")
        self.databar = QtWidgets.QFrame(self.widgetPageSettings)
        self.databar.setGeometry(QtCore.QRect(0, 0, 801, 68))
        self.databar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(172, 172, 172, 228), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.databar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.databar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.databar.setObjectName("databar")
        self.toolButtonDeleteSalesData = QtWidgets.QToolButton(self.databar)
        self.toolButtonDeleteSalesData.setGeometry(QtCore.QRect(290, 10, 50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/remove-from-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonDeleteSalesData.setIcon(icon)
        self.toolButtonDeleteSalesData.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonDeleteSalesData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonDeleteSalesData.setObjectName("toolButtonDeleteSalesData")
        self.toolButtonImportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportDatabase.setGeometry(QtCore.QRect(70, 10, 50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/download-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportDatabase.setIcon(icon1)
        self.toolButtonImportDatabase.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonImportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportDatabase.setObjectName("toolButtonImportDatabase")
        self.toolButtonExportDatabase = QtWidgets.QToolButton(self.databar)
        self.toolButtonExportDatabase.setGeometry(QtCore.QRect(10, 10, 50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/system/database-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExportDatabase.setIcon(icon2)
        self.toolButtonExportDatabase.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonExportDatabase.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonExportDatabase.setObjectName("toolButtonExportDatabase")
        self.toolButtonImportCsvData = QtWidgets.QToolButton(self.databar)
        self.toolButtonImportCsvData.setGeometry(QtCore.QRect(230, 10, 50, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/system/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonImportCsvData.setIcon(icon3)
        self.toolButtonImportCsvData.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonImportCsvData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonImportCsvData.setObjectName("toolButtonImportCsvData")
        self.toolButtonArchiveSettings = QtWidgets.QToolButton(self.databar)
        self.toolButtonArchiveSettings.setGeometry(QtCore.QRect(740, 10, 50, 50))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/system/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonArchiveSettings.setIcon(icon4)
        self.toolButtonArchiveSettings.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonArchiveSettings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonArchiveSettings.setObjectName("toolButtonArchiveSettings")
        self.widgetAppPages.addWidget(self.widgetPageSettings)
        self.widgetPageInfo = QtWidgets.QWidget()
        self.widgetPageInfo.setObjectName("widgetPageInfo")
        self.label_2 = QtWidgets.QLabel(self.widgetPageInfo)
        self.label_2.setGeometry(QtCore.QRect(250, 210, 161, 71))
        self.label_2.setObjectName("label_2")
        self.widgetAppPages.addWidget(self.widgetPageInfo)
        self.widgetPageVisit = QtWidgets.QWidget()
        self.widgetPageVisit.setObjectName("widgetPageVisit")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 490, 781, 59))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gridLayoutWidget_5.setFont(font)
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.widgetCreateOrderLine = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.widgetCreateOrderLine.setContentsMargins(0, 0, 0, 0)
        self.widgetCreateOrderLine.setSpacing(2)
        self.widgetCreateOrderLine.setObjectName("widgetCreateOrderLine")
        self.labelVisitPrice = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitPrice.setFont(font)
        self.labelVisitPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitPrice.setObjectName("labelVisitPrice")
        self.widgetCreateOrderLine.addWidget(self.labelVisitPrice, 0, 5, 1, 1)
        self.labelVisitPcs = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitPcs.setFont(font)
        self.labelVisitPcs.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitPcs.setObjectName("labelVisitPcs")
        self.widgetCreateOrderLine.addWidget(self.labelVisitPcs, 0, 1, 1, 1)
        self.comboVisitLineType = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.comboVisitLineType.setMinimumSize(QtCore.QSize(60, 30))
        self.comboVisitLineType.setMaximumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboVisitLineType.setFont(font)
        self.comboVisitLineType.setEditable(True)
        self.comboVisitLineType.setCurrentText("T")
        self.comboVisitLineType.setMaxCount(4)
        self.comboVisitLineType.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboVisitLineType.setMinimumContentsLength(1)
        self.comboVisitLineType.setObjectName("comboVisitLineType")
        self.comboVisitLineType.addItem("")
        self.comboVisitLineType.addItem("")
        self.comboVisitLineType.addItem("")
        self.comboVisitLineType.addItem("")
        self.widgetCreateOrderLine.addWidget(self.comboVisitLineType, 1, 0, 1, 1)
        self.labelVisitDemoNotSoldPhone = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitDemoNotSoldPhone.setFont(font)
        self.labelVisitDemoNotSoldPhone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitDemoNotSoldPhone.setObjectName("labelVisitDemoNotSoldPhone")
        self.widgetCreateOrderLine.addWidget(self.labelVisitDemoNotSoldPhone, 0, 0, 1, 1)
        self.labelVisitSku = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitSku.setFont(font)
        self.labelVisitSku.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitSku.setObjectName("labelVisitSku")
        self.widgetCreateOrderLine.addWidget(self.labelVisitSku, 0, 3, 1, 1)
        self.labelVisitProduct = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitProduct.setFont(font)
        self.labelVisitProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitProduct.setObjectName("labelVisitProduct")
        self.widgetCreateOrderLine.addWidget(self.labelVisitProduct, 0, 2, 1, 1)
        self.textVisitLineDiscount = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.textVisitLineDiscount.setEnabled(False)
        self.textVisitLineDiscount.setMinimumSize(QtCore.QSize(0, 30))
        self.textVisitLineDiscount.setMaximumSize(QtCore.QSize(50, 30))
        self.textVisitLineDiscount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitLineDiscount.setObjectName("textVisitLineDiscount")
        self.widgetCreateOrderLine.addWidget(self.textVisitLineDiscount, 1, 6, 1, 1)
        self.textVisitLineText = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.textVisitLineText.setMinimumSize(QtCore.QSize(0, 30))
        self.textVisitLineText.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitLineText.setFont(font)
        self.textVisitLineText.setObjectName("textVisitLineText")
        self.widgetCreateOrderLine.addWidget(self.textVisitLineText, 1, 4, 1, 1)
        self.labelVisitText = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitText.setFont(font)
        self.labelVisitText.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitText.setObjectName("labelVisitText")
        self.widgetCreateOrderLine.addWidget(self.labelVisitText, 0, 4, 1, 1)
        self.textVisitLinePrice = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.textVisitLinePrice.setEnabled(False)
        self.textVisitLinePrice.setMinimumSize(QtCore.QSize(0, 30))
        self.textVisitLinePrice.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitLinePrice.setFont(font)
        self.textVisitLinePrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitLinePrice.setObjectName("textVisitLinePrice")
        self.widgetCreateOrderLine.addWidget(self.textVisitLinePrice, 1, 5, 1, 1)
        self.checkVisitSas = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkVisitSas.setEnabled(False)
        self.checkVisitSas.setMinimumSize(QtCore.QSize(20, 25))
        self.checkVisitSas.setMaximumSize(QtCore.QSize(20, 25))
        self.checkVisitSas.setText("")
        self.checkVisitSas.setObjectName("checkVisitSas")
        self.widgetCreateOrderLine.addWidget(self.checkVisitSas, 1, 7, 1, 1)
        self.labelVisitCheckSas = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitCheckSas.setFont(font)
        self.labelVisitCheckSas.setObjectName("labelVisitCheckSas")
        self.widgetCreateOrderLine.addWidget(self.labelVisitCheckSas, 0, 7, 1, 1)
        self.labelVisitDiscount = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelVisitDiscount.setFont(font)
        self.labelVisitDiscount.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVisitDiscount.setObjectName("labelVisitDiscount")
        self.widgetCreateOrderLine.addWidget(self.labelVisitDiscount, 0, 6, 1, 1)
        self.toolButtonVisitAppendLine = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/system/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonVisitAppendLine.setIcon(icon5)
        self.toolButtonVisitAppendLine.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonVisitAppendLine.setObjectName("toolButtonVisitAppendLine")
        self.widgetCreateOrderLine.addWidget(self.toolButtonVisitAppendLine, 1, 8, 1, 1)
        self.toolButtonVisitClearLine = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/system/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonVisitClearLine.setIcon(icon6)
        self.toolButtonVisitClearLine.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonVisitClearLine.setObjectName("toolButtonVisitClearLine")
        self.widgetCreateOrderLine.addWidget(self.toolButtonVisitClearLine, 1, 9, 1, 1)
        self.groupOrderHead = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupOrderHead.setGeometry(QtCore.QRect(400, 0, 400, 260))
        self.groupOrderHead.setObjectName("groupOrderHead")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupOrderHead)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 380, 160))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.widgetVisitHead = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.widgetVisitHead.setContentsMargins(0, 0, 0, 0)
        self.widgetVisitHead.setObjectName("widgetVisitHead")
        self.textVisitProductDemo = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitProductDemo.setFont(font)
        self.textVisitProductDemo.setReadOnly(True)
        self.textVisitProductDemo.setObjectName("textVisitProductDemo")
        self.widgetVisitHead.addWidget(self.textVisitProductDemo, 3, 0, 1, 1)
        self.textVisitDate = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.textVisitDate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDate.setFont(font)
        self.textVisitDate.setReadOnly(True)
        self.textVisitDate.setObjectName("textVisitDate")
        self.widgetVisitHead.addWidget(self.textVisitDate, 0, 0, 1, 1)
        self.textVisitDelAddress2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelAddress2.setFont(font)
        self.textVisitDelAddress2.setObjectName("textVisitDelAddress2")
        self.widgetVisitHead.addWidget(self.textVisitDelAddress2, 2, 1, 1, 1)
        self.textVisitPoNumber = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitPoNumber.setFont(font)
        self.textVisitPoNumber.setObjectName("textVisitPoNumber")
        self.widgetVisitHead.addWidget(self.textVisitPoNumber, 2, 0, 1, 1)
        self.textVisitDelAddress1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelAddress1.setFont(font)
        self.textVisitDelAddress1.setObjectName("textVisitDelAddress1")
        self.widgetVisitHead.addWidget(self.textVisitDelAddress1, 1, 1, 1, 1)
        self.textVisitDelCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelCompany.setFont(font)
        self.textVisitDelCompany.setObjectName("textVisitDelCompany")
        self.widgetVisitHead.addWidget(self.textVisitDelCompany, 0, 1, 1, 1)
        self.textVisitProductSale = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitProductSale.setFont(font)
        self.textVisitProductSale.setReadOnly(True)
        self.textVisitProductSale.setObjectName("textVisitProductSale")
        self.widgetVisitHead.addWidget(self.textVisitProductSale, 4, 0, 1, 1)
        self.textVisitDelCity = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelCity.setFont(font)
        self.textVisitDelCity.setObjectName("textVisitDelCity")
        self.widgetVisitHead.addWidget(self.textVisitDelCity, 4, 1, 1, 1)
        self.textVisitDelZip = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitDelZip.setFont(font)
        self.textVisitDelZip.setObjectName("textVisitDelZip")
        self.widgetVisitHead.addWidget(self.textVisitDelZip, 3, 1, 1, 1)
        self.textVisitBuyer = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitBuyer.setFont(font)
        self.textVisitBuyer.setObjectName("textVisitBuyer")
        self.widgetVisitHead.addWidget(self.textVisitBuyer, 1, 0, 1, 1)
        self.textVisitOrderNote = QtWidgets.QLineEdit(self.groupOrderHead)
        self.textVisitOrderNote.setGeometry(QtCore.QRect(10, 190, 380, 24))
        self.textVisitOrderNote.setMaxLength(100)
        self.textVisitOrderNote.setObjectName("textVisitOrderNote")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupOrderHead)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 220, 380, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTotal.setFont(font)
        self.labelTotal.setObjectName("labelTotal")
        self.gridLayout.addWidget(self.labelTotal, 0, 4, 1, 1)
        self.textVisitSas = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSas.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitSas.setFont(font)
        self.textVisitSas.setReadOnly(True)
        self.textVisitSas.setObjectName("textVisitSas")
        self.gridLayout.addWidget(self.textVisitSas, 0, 3, 1, 1)
        self.labelSas = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSas.setFont(font)
        self.labelSas.setObjectName("labelSas")
        self.gridLayout.addWidget(self.labelSas, 0, 2, 1, 1)
        self.textVisitSale = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitSale.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitSale.setFont(font)
        self.textVisitSale.setReadOnly(True)
        self.textVisitSale.setObjectName("textVisitSale")
        self.gridLayout.addWidget(self.textVisitSale, 0, 1, 1, 1)
        self.textVisitTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textVisitTotal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitTotal.setFont(font)
        self.textVisitTotal.setReadOnly(True)
        self.textVisitTotal.setObjectName("textVisitTotal")
        self.gridLayout.addWidget(self.textVisitTotal, 0, 5, 1, 1)
        self.labelSale = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSale.setFont(font)
        self.labelSale.setObjectName("labelSale")
        self.gridLayout.addWidget(self.labelSale, 0, 0, 1, 1)
        self.groupVisitHead = QtWidgets.QGroupBox(self.widgetPageVisit)
        self.groupVisitHead.setGeometry(QtCore.QRect(0, 0, 400, 260))
        self.groupVisitHead.setObjectName("groupVisitHead")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupVisitHead)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 380, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridCustomerVisit = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridCustomerVisit.setContentsMargins(0, 0, 0, 0)
        self.gridCustomerVisit.setObjectName("gridCustomerVisit")
        self.textVisitCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitCompany.setFont(font)
        self.textVisitCompany.setReadOnly(True)
        self.textVisitCompany.setObjectName("textVisitCompany")
        self.gridCustomerVisit.addWidget(self.textVisitCompany, 0, 0, 1, 1)
        self.textVisitNote = QtWidgets.QTextEdit(self.groupVisitHead)
        self.textVisitNote.setGeometry(QtCore.QRect(10, 70, 380, 110))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitNote.setFont(font)
        self.textVisitNote.setObjectName("textVisitNote")
        self.buttonArchiveVisit = QtWidgets.QPushButton(self.groupVisitHead)
        self.buttonArchiveVisit.setEnabled(True)
        self.buttonArchiveVisit.setGeometry(QtCore.QRect(10, 190, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonArchiveVisit.setFont(font)
        self.buttonArchiveVisit.setAutoDefault(False)
        self.buttonArchiveVisit.setObjectName("buttonArchiveVisit")
        self.textVisitId = QtWidgets.QLineEdit(self.widgetPageVisit)
        self.textVisitId.setEnabled(True)
        self.textVisitId.setGeometry(QtCore.QRect(820, 110, 50, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textVisitId.sizePolicy().hasHeightForWidth())
        self.textVisitId.setSizePolicy(sizePolicy)
        self.textVisitId.setMinimumSize(QtCore.QSize(50, 0))
        self.textVisitId.setMaximumSize(QtCore.QSize(0, 16777215))
        self.textVisitId.setText("")
        self.textVisitId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitId.setReadOnly(True)
        self.textVisitId.setObjectName("textVisitId")
        self.textCustId = QtWidgets.QLineEdit(self.widgetPageVisit)
        self.textCustId.setGeometry(QtCore.QRect(820, 80, 50, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textCustId.sizePolicy().hasHeightForWidth())
        self.textCustId.setSizePolicy(sizePolicy)
        self.textCustId.setMinimumSize(QtCore.QSize(50, 0))
        self.textCustId.setMaximumSize(QtCore.QSize(0, 16777215))
        self.textCustId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textCustId.setObjectName("textCustId")
        self.tableDemo = QtWidgets.QTableWidget(self.widgetPageVisit)
        self.tableDemo.setGeometry(QtCore.QRect(10, 300, 230, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableDemo.setFont(font)
        self.tableDemo.setLocale(QtCore.QLocale(QtCore.QLocale.Danish, QtCore.QLocale.Denmark))
        self.tableDemo.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableDemo.setAlternatingRowColors(True)
        self.tableDemo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableDemo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableDemo.setCornerButtonEnabled(False)
        self.tableDemo.setColumnCount(3)
        self.tableDemo.setObjectName("tableDemo")
        self.tableDemo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableDemo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDemo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDemo.setHorizontalHeaderItem(2, item)
        self.tableDemo.horizontalHeader().setCascadingSectionResizes(True)
        self.tableDemo.horizontalHeader().setDefaultSectionSize(60)
        self.tableDemo.horizontalHeader().setMinimumSectionSize(10)
        self.tableDemo.horizontalHeader().setStretchLastSection(True)
        self.tableDemo.verticalHeader().setMinimumSectionSize(30)
        self.tableDemo.verticalHeader().setStretchLastSection(False)
        self.toolButtonAddDemo = QtWidgets.QToolButton(self.widgetPageVisit)
        self.toolButtonAddDemo.setGeometry(QtCore.QRect(250, 320, 60, 60))
        self.toolButtonAddDemo.setIcon(icon5)
        self.toolButtonAddDemo.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonAddDemo.setObjectName("toolButtonAddDemo")
        self.tableSale = QtWidgets.QTableWidget(self.widgetPageVisit)
        self.tableSale.setGeometry(QtCore.QRect(320, 300, 400, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableSale.setFont(font)
        self.tableSale.setLocale(QtCore.QLocale(QtCore.QLocale.Danish, QtCore.QLocale.Denmark))
        self.tableSale.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableSale.setAlternatingRowColors(True)
        self.tableSale.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableSale.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSale.setCornerButtonEnabled(False)
        self.tableSale.setColumnCount(7)
        self.tableSale.setObjectName("tableSale")
        self.tableSale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSale.setHorizontalHeaderItem(6, item)
        self.tableSale.horizontalHeader().setCascadingSectionResizes(True)
        self.tableSale.horizontalHeader().setDefaultSectionSize(60)
        self.tableSale.horizontalHeader().setMinimumSectionSize(10)
        self.tableSale.horizontalHeader().setStretchLastSection(True)
        self.tableSale.verticalHeader().setMinimumSectionSize(30)
        self.tableSale.verticalHeader().setStretchLastSection(False)
        self.toolButtonAddSale = QtWidgets.QToolButton(self.widgetPageVisit)
        self.toolButtonAddSale.setGeometry(QtCore.QRect(730, 300, 60, 60))
        self.toolButtonAddSale.setIcon(icon5)
        self.toolButtonAddSale.setIconSize(QtCore.QSize(32, 32))
        self.toolButtonAddSale.setObjectName("toolButtonAddSale")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widgetPageVisit)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 260, 380, 32))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboOrderSku = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboOrderSku.setEnabled(True)
        self.comboOrderSku.setMinimumSize(QtCore.QSize(120, 30))
        self.comboOrderSku.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboOrderSku.setFont(font)
        self.comboOrderSku.setEditable(True)
        self.comboOrderSku.setObjectName("comboOrderSku")
        self.gridLayout_2.addWidget(self.comboOrderSku, 0, 3, 1, 1)
        self.comboOrderItem = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboOrderItem.setEnabled(True)
        self.comboOrderItem.setMinimumSize(QtCore.QSize(80, 30))
        self.comboOrderItem.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboOrderItem.setFont(font)
        self.comboOrderItem.setEditable(True)
        self.comboOrderItem.setObjectName("comboOrderItem")
        self.gridLayout_2.addWidget(self.comboOrderItem, 0, 2, 1, 1)
        self.textVisitPcs = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.textVisitPcs.setEnabled(True)
        self.textVisitPcs.setMinimumSize(QtCore.QSize(0, 30))
        self.textVisitPcs.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textVisitPcs.setFont(font)
        self.textVisitPcs.setMaxLength(4)
        self.textVisitPcs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textVisitPcs.setObjectName("textVisitPcs")
        self.gridLayout_2.addWidget(self.textVisitPcs, 0, 1, 1, 1)
        self.widgetAppPages.addWidget(self.widgetPageVisit)
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.topbar.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(186, 186, 186, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: rgb(175, 175, 175);\n"
"    border: 1px rgb(235, 235, 235);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(195, 195, 195);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}\n"
"\n"
"QToolButton:hover:checked {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border: 1px rgb(205, 205, 205);\n"
"}")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.toolButtonReport = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReport.setGeometry(QtCore.QRect(360, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonReport.setFont(font)
        self.toolButtonReport.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/system/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReport.setIcon(icon7)
        self.toolButtonReport.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReport.setCheckable(True)
        self.toolButtonReport.setChecked(False)
        self.toolButtonReport.setAutoExclusive(True)
        self.toolButtonReport.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonReport.setObjectName("toolButtonReport")
        self.toolButtonCustomers = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomers.setGeometry(QtCore.QRect(10, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomers.setFont(font)
        self.toolButtonCustomers.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/system/companies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomers.setIcon(icon8)
        self.toolButtonCustomers.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomers.setCheckable(True)
        self.toolButtonCustomers.setAutoExclusive(True)
        self.toolButtonCustomers.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomers.setObjectName("toolButtonCustomers")
        self.toolButtonCustomer = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomer.setGeometry(QtCore.QRect(80, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomer.setFont(font)
        self.toolButtonCustomer.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/system/company.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomer.setIcon(icon9)
        self.toolButtonCustomer.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomer.setCheckable(True)
        self.toolButtonCustomer.setAutoExclusive(True)
        self.toolButtonCustomer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomer.setObjectName("toolButtonCustomer")
        self.toolButtonCustomerVisits = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomerVisits.setGeometry(QtCore.QRect(150, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomerVisits.setFont(font)
        self.toolButtonCustomerVisits.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/system/order-history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomerVisits.setIcon(icon10)
        self.toolButtonCustomerVisits.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomerVisits.setCheckable(True)
        self.toolButtonCustomerVisits.setAutoExclusive(True)
        self.toolButtonCustomerVisits.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomerVisits.setObjectName("toolButtonCustomerVisits")
        self.toolButtonPricelist = QtWidgets.QToolButton(self.topbar)
        self.toolButtonPricelist.setGeometry(QtCore.QRect(290, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonPricelist.setFont(font)
        self.toolButtonPricelist.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/system/catalog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPricelist.setIcon(icon11)
        self.toolButtonPricelist.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonPricelist.setCheckable(True)
        self.toolButtonPricelist.setAutoExclusive(True)
        self.toolButtonPricelist.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonPricelist.setObjectName("toolButtonPricelist")
        self.toolButtonReports = QtWidgets.QToolButton(self.topbar)
        self.toolButtonReports.setGeometry(QtCore.QRect(430, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonReports.setFont(font)
        self.toolButtonReports.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/system/reports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonReports.setIcon(icon12)
        self.toolButtonReports.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonReports.setCheckable(True)
        self.toolButtonReports.setAutoExclusive(True)
        self.toolButtonReports.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonReports.setObjectName("toolButtonReports")
        self.toolButtonInfo = QtWidgets.QToolButton(self.topbar)
        self.toolButtonInfo.setGeometry(QtCore.QRect(650, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonInfo.setFont(font)
        self.toolButtonInfo.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/system/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonInfo.setIcon(icon13)
        self.toolButtonInfo.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonInfo.setCheckable(True)
        self.toolButtonInfo.setAutoExclusive(True)
        self.toolButtonInfo.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonInfo.setObjectName("toolButtonInfo")
        self.toolButtonSettings = QtWidgets.QToolButton(self.topbar)
        self.toolButtonSettings.setGeometry(QtCore.QRect(580, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonSettings.setFont(font)
        self.toolButtonSettings.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/system/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSettings.setIcon(icon14)
        self.toolButtonSettings.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonSettings.setCheckable(True)
        self.toolButtonSettings.setAutoExclusive(True)
        self.toolButtonSettings.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonSettings.setObjectName("toolButtonSettings")
        self.toolButtonExit = QtWidgets.QToolButton(self.topbar)
        self.toolButtonExit.setGeometry(QtCore.QRect(720, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonExit.setFont(font)
        self.toolButtonExit.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/system/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonExit.setIcon(icon15)
        self.toolButtonExit.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonExit.setCheckable(True)
        self.toolButtonExit.setAutoExclusive(True)
        self.toolButtonExit.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonExit.setObjectName("toolButtonExit")
        self.toolButtonCustomerVisit = QtWidgets.QToolButton(self.topbar)
        self.toolButtonCustomerVisit.setEnabled(True)
        self.toolButtonCustomerVisit.setGeometry(QtCore.QRect(220, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.toolButtonCustomerVisit.setFont(font)
        self.toolButtonCustomerVisit.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/system/ordering.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCustomerVisit.setIcon(icon16)
        self.toolButtonCustomerVisit.setIconSize(QtCore.QSize(48, 48))
        self.toolButtonCustomerVisit.setCheckable(True)
        self.toolButtonCustomerVisit.setAutoExclusive(True)
        self.toolButtonCustomerVisit.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCustomerVisit.setObjectName("toolButtonCustomerVisit")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.widgetAppPages.setCurrentIndex(8)
        self.comboVisitLineType.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Eordre"))
        self.widgetAppCustomers.headerItem().setText(0, _translate("mainWindow", "Konto"))
        self.widgetAppCustomers.headerItem().setText(1, _translate("mainWindow", "Telefon"))
        self.widgetAppCustomers.headerItem().setText(2, _translate("mainWindow", "Telefon"))
        self.widgetAppCustomers.headerItem().setText(3, _translate("mainWindow", "Firma"))
        self.widgetAppCustomers.headerItem().setText(4, _translate("mainWindow", "Post"))
        self.widgetAppCustomers.headerItem().setText(5, _translate("mainWindow", "Bynavn"))
        self.textCustomerName.setToolTip(_translate("mainWindow", "navn for ny kunde"))
        self.textCustomerName.setStatusTip(_translate("mainWindow", "Her indsættes firmanavn for kunde der skal oprettes"))
        self.textCustomerName.setPlaceholderText(_translate("mainWindow", "navn"))
        self.textCustomerPhone1.setToolTip(_translate("mainWindow", "telefon for ny kunde"))
        self.textCustomerPhone1.setStatusTip(_translate("mainWindow", "Her indsættes telefon nummer for kunde der skal oprettes\n"
"                                                "))
        self.textCustomerPhone1.setPlaceholderText(_translate("mainWindow", "telefon"))
        self.buttonCreateCustomer.setToolTip(_translate("mainWindow", "Opret ny kunde"))
        self.buttonCreateCustomer.setStatusTip(_translate("mainWindow", "Udfyld felterne og tryk her for at oprette firma"))
        self.buttonCreateCustomer.setText(_translate("mainWindow", "Opret kunde"))
        self.textFactor.setToolTip(_translate("mainWindow", "Faktor"))
        self.textFactor.setStatusTip(_translate("mainWindow", "Ved salg bliver liste priser ganget med\n"
"                                                                        faktor\n"
"                                                                    "))
        self.textFactor.setPlaceholderText(_translate("mainWindow", "faktor"))
        self.textAddress2.setToolTip(_translate("mainWindow", "Udvidet adresse"))
        self.textAddress2.setStatusTip(_translate("mainWindow", "Dette felt er udvidet adresse"))
        self.textAddress2.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone1.setToolTip(_translate("mainWindow", "Primær telefon"))
        self.textPhone1.setStatusTip(_translate("mainWindow", "Dette felt er primær telefon til kunde\n"
"                                                                    "))
        self.textPhone1.setPlaceholderText(_translate("mainWindow", "primær telefon"))
        self.textEmail.setToolTip(_translate("mainWindow", "Epost adresse"))
        self.textEmail.setStatusTip(_translate("mainWindow", "Dette felt er epost adresse for kunde\n"
"                                                                    "))
        self.textEmail.setPlaceholderText(_translate("mainWindow", "epost adresse"))
        self.textAddress1.setToolTip(_translate("mainWindow", "Kundens adresse"))
        self.textAddress1.setStatusTip(_translate("mainWindow", "Dette felt er kunde adresse"))
        self.textAddress1.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.textPhone2.setToolTip(_translate("mainWindow", "Anden telefon"))
        self.textPhone2.setStatusTip(_translate("mainWindow", "Dette felt er mobil eller anden telefon til\n"
"                                                                        kunde\n"
"                                                                    "))
        self.textPhone2.setPlaceholderText(_translate("mainWindow", "mobil telefon"))
        self.textCompany.setToolTip(_translate("mainWindow", "Firmanavn"))
        self.textCompany.setStatusTip(_translate("mainWindow", "Dette felt er kunde navn"))
        self.textCompany.setPlaceholderText(_translate("mainWindow", "firma navn"))
        self.textAccount.setToolTip(_translate("mainWindow", "Kundekonto"))
        self.textAccount.setStatusTip(_translate("mainWindow", "Dette felt er konto for kunde"))
        self.textAccount.setPlaceholderText(_translate("mainWindow", "konto"))
        self.textCityName.setToolTip(_translate("mainWindow", "Bynavn"))
        self.textCityName.setStatusTip(_translate("mainWindow", "Dette felt er bynavn for kunde"))
        self.textCityName.setPlaceholderText(_translate("mainWindow", "by navn"))
        self.textZipCode.setToolTip(_translate("mainWindow", "Postnummer"))
        self.textZipCode.setStatusTip(_translate("mainWindow", "Dette felt er postnummer for kunde"))
        self.textZipCode.setPlaceholderText(_translate("mainWindow", "post nummer"))
        self.widgetCustomerContacts.headerItem().setText(0, _translate("mainWindow", "Navn"))
        self.widgetCustomerContacts.headerItem().setText(1, _translate("mainWindow", "Telefon"))
        self.widgetCustomerContacts.headerItem().setText(2, _translate("mainWindow", "Afdeling"))
        self.widgetCustomerContacts.headerItem().setText(3, _translate("mainWindow", "Email"))
        self.widgetCustomerContacts.headerItem().setText(4, _translate("mainWindow", "Info"))
        self.buttonArchiveContacts.setText(_translate("mainWindow", "Arkiver kontakter"))
        self.buttonCreateContact.setText(_translate("mainWindow", "Tilføj kontakt ..."))
        self.buttonArchiveCustomer.setToolTip(_translate("mainWindow", "Arkiver ændringer"))
        self.buttonArchiveCustomer.setStatusTip(_translate("mainWindow", "Tryk her for at gemme rettelser i\n"
"                                                                        databasen\n"
"                                                                    "))
        self.buttonArchiveCustomer.setText(_translate("mainWindow", "Arkiver kunde"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Varenr"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Total"))
        item = self.widgetCustomerProducts.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Bestil"))
        self.widgetArchivedVisits.headerItem().setText(0, _translate("mainWindow", "Id"))
        self.widgetArchivedVisits.headerItem().setText(1, _translate("mainWindow", "Dato"))
        self.widgetArchivedVisits.headerItem().setText(2, _translate("mainWindow", "Navn"))
        self.widgetArchivedVisits.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.widgetArchivedVisits.headerItem().setText(4, _translate("mainWindow", "Salg"))
        self.widgetArchivedVisits.headerItem().setText(5, _translate("mainWindow", "Ordre note"))
        self.widgetArchivedOrderLines.headerItem().setText(0, _translate("mainWindow", "*"))
        self.widgetArchivedOrderLines.headerItem().setText(1, _translate("mainWindow", "Ant"))
        self.widgetArchivedOrderLines.headerItem().setText(2, _translate("mainWindow", "SKU"))
        self.widgetArchivedOrderLines.headerItem().setText(3, _translate("mainWindow", "Vare"))
        self.widgetArchivedOrderLines.headerItem().setText(4, _translate("mainWindow", "Pris"))
        self.widgetArchivedOrderLines.headerItem().setText(5, _translate("mainWindow", "%"))
        self.widgetArchivedOrderLines.headerItem().setText(6, _translate("mainWindow", "Linje note"))
        self.labelArchivedSend.setText(_translate("mainWindow", "Afsl."))
        self.labelArchivedOrderSale.setText(_translate("mainWindow", "Salg"))
        self.labelArchivedSasAmount.setText(_translate("mainWindow", "SAS"))
        self.labelArchivedOrderTotal.setText(_translate("mainWindow", "Total"))
        self.labelArchivedPurchaseOrder.setText(_translate("mainWindow", "Rekv."))
        self.labelArchivedApproved.setText(_translate("mainWindow", "Godk."))
        self.buttonCreateVisit.setText(_translate("mainWindow", "Tilføj besøg ..."))
        self.widgetPricelist.headerItem().setText(1, _translate("mainWindow", "Varenr."))
        self.widgetPricelist.headerItem().setText(2, _translate("mainWindow", "Varetekst"))
        self.widgetPricelist.headerItem().setText(3, _translate("mainWindow", "1 stk"))
        self.widgetPricelist.headerItem().setText(4, _translate("mainWindow", "2 stk"))
        self.widgetPricelist.headerItem().setText(5, _translate("mainWindow", "4 stk"))
        self.widgetPricelist.headerItem().setText(6, _translate("mainWindow", "6 stk"))
        self.widgetPricelist.headerItem().setText(7, _translate("mainWindow", "8 stk"))
        self.widgetPricelist.headerItem().setText(8, _translate("mainWindow", "12 stk"))
        self.widgetPricelist.headerItem().setText(9, _translate("mainWindow", "24 stk"))
        self.widgetPricelist.headerItem().setText(10, _translate("mainWindow", "48 stk"))
        self.widgetPricelist.headerItem().setText(11, _translate("mainWindow", "96 stk"))
        self.widgetPricelist.headerItem().setText(12, _translate("mainWindow", "Netto"))
        __sortingEnabled = self.widgetPricelist.isSortingEnabled()
        self.widgetPricelist.setSortingEnabled(False)
        self.widgetPricelist.topLevelItem(0).setText(0, _translate("mainWindow", "sa"))
        self.widgetPricelist.topLevelItem(0).setText(1, _translate("mainWindow", "01,0108"))
        self.widgetPricelist.topLevelItem(0).setText(2, _translate("mainWindow", "Lim-Spray"))
        self.widgetPricelist.topLevelItem(0).setText(3, _translate("mainWindow", "123"))
        self.widgetPricelist.topLevelItem(0).setText(8, _translate("mainWindow", "108"))
        self.widgetPricelist.topLevelItem(0).setText(9, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(0).setText(12, _translate("mainWindow", "106"))
        self.widgetPricelist.topLevelItem(1).setText(0, _translate("mainWindow", "qba"))
        self.widgetPricelist.topLevelItem(1).setText(1, _translate("mainWindow", "01,0136"))
        self.widgetPricelist.topLevelItem(1).setText(2, _translate("mainWindow", "Activator Quick Bond"))
        self.widgetPricelist.topLevelItem(1).setText(3, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(6, _translate("mainWindow", "181"))
        self.widgetPricelist.topLevelItem(1).setText(8, _translate("mainWindow", "169"))
        self.widgetPricelist.topLevelItem(1).setText(12, _translate("mainWindow", "161"))
        self.widgetPricelist.setSortingEnabled(__sortingEnabled)
        self.textPricelistLocalDate.setToolTip(_translate("mainWindow", "Prisliste synkroniseret"))
        self.textPricelistLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af prisliste"))
        self.textPricelistLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonGetPricelist.setText(_translate("mainWindow", "Priser"))
        self.textPricelistServerDate.setToolTip(_translate("mainWindow", "Tilgængelig prisliste"))
        self.textPricelistServerDate.setStatusTip(_translate("mainWindow", "Dette er datoen for serverens prisliste"))
        self.textPricelistServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonGetCustomers.setText(_translate("mainWindow", "Kunder"))
        self.textCustomerLocalDate.setToolTip(_translate("mainWindow", "Kundeliste synkroniseret"))
        self.textCustomerLocalDate.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af kundeliste"))
        self.textCustomerLocalDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.textCustomerServerDate.setToolTip(_translate("mainWindow", "Tilgængelig kundeliste"))
        self.textCustomerServerDate.setStatusTip(_translate("mainWindow", "Dette datoen for serverens kundeliste"))
        self.textCustomerServerDate.setPlaceholderText(_translate("mainWindow", "dato"))
        self.buttonCreateReport.setToolTip(_translate("mainWindow", "Opret dagsrapport"))
        self.buttonCreateReport.setStatusTip(_translate("mainWindow", "Her opretter du en dagsrapport datoen i feltet"))
        self.buttonCreateReport.setText(_translate("mainWindow", "Opret dagsrapport"))
        self.textWorkdate.setToolTip(_translate("mainWindow", "Arbejdsdato"))
        self.textWorkdate.setStatusTip(_translate("mainWindow", "Dette er systemets arbejdsdato"))
        self.textWorkdate.setPlaceholderText(_translate("mainWindow", "arbejdsdato"))
        self.treeWidget_2.headerItem().setText(0, _translate("mainWindow", "Dagens besøg"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("mainWindow", "AUDI Specialisten Aps"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("mainWindow", "Mixer Nozzle"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("mainWindow", "SP 200"))
        self.treeWidget_2.topLevelItem(0).child(2).setText(0, _translate("mainWindow", "MS 1000"))
        self.treeWidget_2.topLevelItem(0).child(3).setText(0, _translate("mainWindow", "Multi Clean"))
        self.treeWidget_2.topLevelItem(0).child(4).setText(0, _translate("mainWindow", "Zinc Coat"))
        self.treeWidget_2.topLevelItem(0).child(5).setText(0, _translate("mainWindow", "Multiflex Co. Plus 1L Sort"))
        self.treeWidget_2.topLevelItem(0).child(6).setText(0, _translate("mainWindow", "Top Fix Sort"))
        self.treeWidget_2.topLevelItem(0).child(7).setText(0, _translate("mainWindow", "Linen Tape"))
        self.treeWidget_2.topLevelItem(0).child(8).setText(0, _translate("mainWindow", "1.L.KLAR Hi-Temp Wax PRO"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.treeWidget.headerItem().setText(1, _translate("mainWindow", "Besøg"))
        self.treeWidget.headerItem().setText(2, _translate("mainWindow", "Salg"))
        self.treeWidget.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.treeWidget.headerItem().setText(4, _translate("mainWindow", "Oms"))
        self.treeWidget.headerItem().setText(5, _translate("mainWindow", "Supervisor"))
        self.treeWidget.headerItem().setText(6, _translate("mainWindow", "Km"))
        self.groupSalesPerson.setTitle(_translate("mainWindow", "Sælger"))
        self.textAppUserCountry.setPlaceholderText(_translate("mainWindow", "landkode: dk"))
        self.textAppUserPass.setPlaceholderText(_translate("mainWindow", "din adgangs frase"))
        self.textAppUserMail.setPlaceholderText(_translate("mainWindow", "brugers mail adresse: email@domæne.tld"))
        self.groupInternalServers.setTitle(_translate("mainWindow", "Intern mail og data server"))
        self.checkServerData.setText(_translate("mainWindow", "Ved programstart kontroller server data"))
        self.textAppDataServer.setPlaceholderText(_translate("mainWindow", "webserver: http://localhost:8080"))
        self.textAppMailOrderTo.setPlaceholderText(_translate("mainWindow", "modtager email: email@domain.tld"))
        self.textAppMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textAppMailServer.setPlaceholderText(_translate("mainWindow", "post server: mail.domain.tld"))
        self.groupExternalServer.setTitle(_translate("mainWindow", "Ekstern mailserver"))
        self.textExtMailServerUser.setPlaceholderText(_translate("mainWindow", "post server: brugernavn"))
        self.textExtMailServerPort.setPlaceholderText(_translate("mainWindow", "port: 25"))
        self.textExtMailServerPass.setPlaceholderText(_translate("mainWindow", "post server: adgangskode"))
        self.textExtMailServer.setPlaceholderText(_translate("mainWindow", "post server: server.domain.tld"))
        self.toolButtonDeleteSalesData.setText(_translate("mainWindow", "SLET"))
        self.toolButtonImportDatabase.setText(_translate("mainWindow", "Import"))
        self.toolButtonExportDatabase.setText(_translate("mainWindow", "Eksport"))
        self.toolButtonImportCsvData.setText(_translate("mainWindow", "CSV"))
        self.toolButtonArchiveSettings.setText(_translate("mainWindow", "Gem"))
        self.label_2.setText(_translate("mainWindow", "about page"))
        self.labelVisitPrice.setText(_translate("mainWindow", "Pris"))
        self.labelVisitPcs.setText(_translate("mainWindow", "Antal"))
        self.comboVisitLineType.setToolTip(_translate("mainWindow", "Demo|Ny|Salg|Tekst"))
        self.comboVisitLineType.setItemText(0, _translate("mainWindow", "D"))
        self.comboVisitLineType.setItemText(1, _translate("mainWindow", "N"))
        self.comboVisitLineType.setItemText(2, _translate("mainWindow", "S"))
        self.comboVisitLineType.setItemText(3, _translate("mainWindow", "T"))
        self.labelVisitDemoNotSoldPhone.setToolTip(_translate("mainWindow", "Demo Ikke Solgt Telefon"))
        self.labelVisitDemoNotSoldPhone.setText(_translate("mainWindow", "D.I.S.T"))
        self.labelVisitSku.setText(_translate("mainWindow", "Varenr"))
        self.labelVisitProduct.setText(_translate("mainWindow", "Produkt"))
        self.labelVisitText.setText(_translate("mainWindow", "Tekst"))
        self.labelVisitCheckSas.setText(_translate("mainWindow", "SAS"))
        self.labelVisitDiscount.setText(_translate("mainWindow", "%"))
        self.toolButtonVisitAppendLine.setText(_translate("mainWindow", "..."))
        self.toolButtonVisitClearLine.setText(_translate("mainWindow", "..."))
        self.groupOrderHead.setTitle(_translate("mainWindow", "Ordrehoved"))
        self.textVisitProductDemo.setPlaceholderText(_translate("mainWindow", "Produkt demo"))
        self.textVisitDate.setPlaceholderText(_translate("mainWindow", "Ordre dato"))
        self.textVisitDelAddress2.setPlaceholderText(_translate("mainWindow", "Lev. adresse 2"))
        self.textVisitPoNumber.setPlaceholderText(_translate("mainWindow", "Rekvisition"))
        self.textVisitDelAddress1.setPlaceholderText(_translate("mainWindow", "Lev. adresse 1"))
        self.textVisitDelCompany.setPlaceholderText(_translate("mainWindow", "Lev. til"))
        self.textVisitProductSale.setPlaceholderText(_translate("mainWindow", "Produkt salg"))
        self.textVisitDelCity.setPlaceholderText(_translate("mainWindow", "Lev. bynavn"))
        self.textVisitDelZip.setPlaceholderText(_translate("mainWindow", "Lev. postnummer"))
        self.textVisitBuyer.setPlaceholderText(_translate("mainWindow", "Indkøber"))
        self.textVisitOrderNote.setPlaceholderText(_translate("mainWindow", "Ordre note"))
        self.labelTotal.setText(_translate("mainWindow", "Total"))
        self.labelSas.setText(_translate("mainWindow", "SAS"))
        self.labelSale.setText(_translate("mainWindow", "Salg"))
        self.groupVisitHead.setTitle(_translate("mainWindow", "Besøg"))
        self.textVisitNote.setPlaceholderText(_translate("mainWindow", "Besøgs note"))
        self.buttonArchiveVisit.setText(_translate("mainWindow", "Arkiver"))
        self.textVisitId.setPlaceholderText(_translate("mainWindow", "visitid"))
        self.textCustId.setPlaceholderText(_translate("mainWindow", "custid"))
        self.tableDemo.setToolTip(_translate("mainWindow", "Demo "))
        item = self.tableDemo.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "*"))
        item = self.tableDemo.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.tableDemo.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Nummer"))
        self.toolButtonAddDemo.setText(_translate("mainWindow", "..."))
        self.tableSale.setToolTip(_translate("mainWindow", "Demo "))
        item = self.tableSale.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "*"))
        item = self.tableSale.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Ant"))
        item = self.tableSale.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Vare"))
        item = self.tableSale.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Nummer"))
        item = self.tableSale.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Pris"))
        item = self.tableSale.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Rabat"))
        item = self.tableSale.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Sas"))
        self.toolButtonAddSale.setText(_translate("mainWindow", "..."))
        self.label.setText(_translate("mainWindow", "Produkt valg"))
        self.textVisitPcs.setPlaceholderText(_translate("mainWindow", "antal"))
        self.toolButtonReport.setToolTip(_translate("mainWindow", "Dagens rapport"))
        self.toolButtonCustomers.setToolTip(_translate("mainWindow", "Kunde liste"))
        self.toolButtonCustomer.setToolTip(_translate("mainWindow", "Kunde"))
        self.toolButtonCustomerVisits.setToolTip(_translate("mainWindow", "Kundebesøg"))
        self.toolButtonPricelist.setToolTip(_translate("mainWindow", "Prisliste"))
        self.toolButtonReports.setToolTip(_translate("mainWindow", "Rapporter"))
        self.toolButtonInfo.setToolTip(_translate("mainWindow", "Info"))
        self.toolButtonSettings.setToolTip(_translate("mainWindow", "Indstillinger"))
        self.toolButtonExit.setToolTip(_translate("mainWindow", "Afslut"))
        self.toolButtonCustomerVisit.setToolTip(_translate("mainWindow", "Åben ordre/besøg"))

from . import system_rc
